Repository aXenDeveloper/vitnode, pull requests merged in 2024-07, with the labels that each got.

#393 refactor(backend): Authorization middleware for AdminCP
  LICENSE.md
  README.md
  apps/backend/schema.gql
  apps/docs/assets/logo/vitnode_logo_dark.svg
  apps/docs/assets/logo/vitnode_logo_light.svg
  apps/frontend/middleware.ts
  packages/backend/README.md
  packages/backend/src/core/members/members.module.ts
  packages/backend/src/core/members/sign_up/functions/generate-avatar-color.ts
  packages/backend/src/core/members/sign_up/sign_up.resolver.ts
  packages/backend/src/core/sessions/sessions.module.ts
  packages/backend/src/core/sessions/sign_up/dto/sign_up.args.ts
  packages/backend/src/core/sessions/sign_up/dto/sign_up.obj.ts
  packages/backend/src/core/sessions/sign_up/helpers/avatar-color.service.ts
  packages/backend/src/core/sessions/sign_up/sign_up.resolver.ts
  packages/backend/src/core/sessions/sign_up/sign_up.service.ts
  packages/create-vitnode-app/README.md
  packages/eslint-config-vitnode/README.md
  packages/frontend/README.md
  packages/frontend/src/graphql/graphql.ts
  packages/frontend/src/graphql/mutations/sessions/core_members__sign_up.gql
  packages/frontend/src/hooks/core/sign/up/mutation-api.ts
  packages/frontend/src/middleware.ts
  packages/frontend/src/views/admin/layout/admin-layout.tsx
  packages/shared/README.md
  packages/shared/src/colors.ts
Labels: 🚀 Performerce

#397 fix(frontend): Display dynamic icons on RSC
  apps/backend/src/plugins/blog/config.json
  apps/frontend/app/[locale]/(main)/page.tsx
  packages/frontend/src/components/icon/icon-client.tsx
  packages/frontend/src/components/icon/icon.tsx
  packages/frontend/src/components/icon/input/content/icons/icons.tsx
  packages/frontend/src/views/admin/layout/auth/nav/nav-admin.tsx
  packages/frontend/src/views/theme/layout/nav/item.tsx
  packages/frontend/src/views/theme/layout/nav/nav.tsx
  packages/frontend/src/views/theme/layout/theme-layout.tsx
Labels: 🐞 Bug

#395 refactor(frontend): Drag & Drop List
  apps/backend/src/plugins/blog/config.json
  apps/frontend/middleware.ts
  apps/frontend/plugins/blog/admin/views/categories/categories-view.tsx
  packages/frontend/src/components/drag&drop-item.tsx
  packages/frontend/src/components/icon/icon-client.tsx
  packages/frontend/src/components/icon/icon.tsx
  packages/frontend/src/components/icon/input/content/icons/icons.tsx
  packages/frontend/src/middleware.ts
  packages/frontend/src/views/admin/layout/auth/auth-admin-layout.tsx
  packages/frontend/src/views/admin/layout/auth/nav/item/item.tsx
  packages/frontend/src/views/admin/layout/auth/nav/item/link.tsx
  packages/frontend/src/views/admin/layout/auth/nav/nav-admin.tsx
  packages/frontend/src/views/admin/views/core/styles/nav/table/item.tsx
  packages/frontend/src/views/admin/views/core/styles/nav/table/table.tsx
  packages/frontend/tsconfig.json
Labels: 🚀 Performerce

#398 feat(backend): Add send email mutation with hash key to reset password
  apps/backend/schema.gql
  apps/backend/src/plugins/core/admin/database/schema/users.ts
  apps/docs/pages/docs/_meta.json
  apps/docs/pages/docs/email.mdx
  apps/docs/pages/docs/emails.mdx
  apps/frontend/plugins/admin/langs/en.json
  apps/frontend/plugins/admin/langs/pl.json
  apps/frontend/plugins/core/langs/en.json
  apps/frontend/plugins/core/langs/pl.json
  packages/backend/src/app.module.ts
  packages/backend/src/core/admin/admin.module.ts
  packages/backend/src/core/admin/email/email.module.ts
  packages/backend/src/core/admin/email/mail.service.ts
  packages/backend/src/core/admin/email/send/send.service.ts
  packages/backend/src/core/admin/email/settings/show/show.service.ts
  packages/backend/src/core/admin/email/settings/test/dto/test.args.ts
  packages/backend/src/core/admin/email/settings/test/test.resolver.ts
  packages/backend/src/core/admin/email/settings/test/test.service.ts
  packages/backend/src/core/members/members.module.ts
  packages/backend/src/core/members/reset_password/create_key/_email/content.tsx
  packages/backend/src/core/members/reset_password/create_key/create_key.resolver.ts
  packages/backend/src/core/members/reset_password/create_key/create_key.service.ts
  packages/backend/src/core/members/reset_password/create_key/dto/create_key.args.ts
  packages/backend/src/decorators/user.decorator.ts
  packages/backend/src/providers/email/email.ts
  packages/backend/src/providers/email/template/_components/header.tsx
  packages/backend/src/providers/email/template/email-template.tsx
  packages/backend/src/templates/core/admin/database/schema/users.ts
  packages/frontend/src/graphql/graphql.ts
  packages/frontend/src/graphql/mutations/admin/settings/email/admin__core_email_settings__test.gql
  packages/frontend/src/graphql/queries/admin/admin__sessions__authorization.gql
  packages/frontend/src/graphql/queries/admin/members/staff/admin__core_staff_administrators__show.gql
  packages/frontend/src/graphql/queries/admin/members/staff/admin__core_staff_moderators__show.gql
  packages/frontend/src/graphql/queries/core_sessions__authorization.gql
  packages/frontend/src/views/admin/views/core/settings/email/actions/testing/content.tsx
  packages/frontend/src/views/admin/views/core/settings/email/actions/testing/hooks/use-testing-email-admin.tsx
  packages/frontend/src/views/admin/views/core/settings/email/email-settings-admin-view.tsx
  packages/frontend/src/views/admin/views/core/settings/email/hooks/use-email-settings-form-admin.ts
  packages/frontend/src/views/admin/views/members/staff/administrators/table/table.tsx
Labels: 💡 Feature

#403 feat(backend): Add Helmet
  apps/docs/theme.config.tsx
  apps/docs/views/home/features/sections/secure.tsx
  packages/backend/package.json
  packages/backend/src/main.ts
  packages/frontend/src/views/admin/views/core/settings/security/captcha/content.tsx
  pnpm-lock.yaml
Labels: 💡 Feature

#404 feat(backend): Add throttler NestJS
  apps/docs/views/home/features/sections/secure.tsx
  apps/frontend/utils/graphql.ts
  packages/backend/package.json
  packages/backend/src/app.module.ts
  packages/backend/src/core/languages/show/show.resolver.ts
  packages/backend/src/core/middleware/show/show.resolver.ts
  packages/backend/src/core/plugins/show/show.resolver.ts
  packages/backend/src/core/settings/show/show.resolver.ts
  packages/backend/src/main.ts
  packages/backend/src/utils/guards/gql-throttler.guard.ts
  packages/frontend/src/graphql/queries/core_sessions__authorization.gql
  pnpm-lock.yaml
Labels: 💡 Feature

#401 feat: Changing password
  packages/backend/src/core/members/members.module.ts
  packages/backend/src/core/members/reset_password/change_password/change_password.resolver.ts
  packages/backend/src/core/members/reset_password/change_password/change_password.service.ts
  packages/backend/src/core/members/reset_password/change_password/dto/change_password.args.ts
  packages/backend/src/core/sessions/encrypt_password.ts
  packages/backend/src/core/sessions/sign_up/sign_up.service.ts
Labels: 💡 Feature

#410 perf: Change from npm publish to pnpm publish
  .github/workflows/publish.yaml
Labels: 🚀 Performerce

#413 perf(frontend): Move css admin file to package
  apps/frontend/app/[locale]/(admin)/admin/install/layout.tsx
  apps/frontend/app/[locale]/(admin)/error.tsx
  apps/frontend/app/[locale]/(admin)/layout.tsx
  apps/frontend/app/[locale]/(utils)/admin/theme-editor/layout.tsx
  apps/frontend/next.config.ts
  apps/frontend/package.json
  packages/frontend/.npmignore
  packages/frontend/next.config.ts
  packages/frontend/package.json
  packages/frontend/src/global.css
  packages/frontend/src/views/admin/views/install/install-configs-view.tsx
  packages/frontend/src/views/admin/views/install/layout.tsx
  packages/frontend/tsconfig.json
  pnpm-lock.yaml
Labels: 🚀 Performerce

#414 perf: Improve dependencies for packages
  apps/backend/package.json
  apps/docs/package.json
  apps/frontend/package.json
  packages/backend/package.json
  packages/backend/src/core/admin/plugins/delete/contents.ts
  packages/create-vitnode-app/package.json
  packages/eslint-config-typescript-vitnode/package.json
  packages/frontend/package.json
  packages/frontend/src/views/admin/views/core/plugins/views/dev/overview/content.tsx
  packages/shared/README.md
  packages/shared/package.json
  pnpm-lock.yaml
Labels: 🚀 Performerce

#409 refactor(frontend): Aside AdminCP
  packages/create-vitnode-app/templates/basic/apps/frontend/global.d.ts
  packages/eslint-config-typescript-vitnode/.eslintrc.shared.json
  packages/frontend/package.json
  packages/frontend/src/components/logo-vitnode.tsx
  packages/frontend/src/components/ui/radio-group.tsx
  packages/frontend/src/components/ui/scroll-area.tsx
  packages/frontend/src/components/ui/sheet.tsx
  packages/frontend/src/views/admin/layout/auth/aside/aside.tsx
  packages/frontend/src/views/admin/layout/auth/aside/avatar.tsx
  packages/frontend/src/views/admin/layout/auth/aside/hooks/mutation-api.ts
  packages/frontend/src/views/admin/layout/auth/auth-admin-layout.tsx
  packages/frontend/src/views/admin/layout/auth/header/drawer/drawer.tsx
  packages/frontend/src/views/admin/layout/auth/header/drawer/item.tsx
  packages/frontend/src/views/admin/layout/auth/header/header-admin.tsx
  packages/frontend/src/views/admin/layout/auth/header/header.tsx
  packages/frontend/src/views/admin/layout/auth/nav/item/item.tsx
  packages/frontend/src/views/admin/layout/auth/nav/item/link.tsx
  packages/frontend/src/views/admin/layout/auth/nav/wrapper.tsx
  pnpm-lock.yaml
Labels: 🧱 Refactor

#418 perf(packages): Reduce dependencies & remove react-use
  packages/backend/package.json
  packages/create-vitnode-app/templates/create-packages-json.ts
  packages/frontend/package.json
  packages/frontend/src/components/ui/form.tsx
  packages/frontend/src/helpers/use-before-unload.ts
  pnpm-lock.yaml
Labels: 🚀 Performerce

#420 feat(frontend): Add tag input
  apps/docs/content/docs/ui/tag-input.mdx
  apps/docs/content/docs/ui/test.mdx
  packages/frontend/src/components/ui/badge.tsx
  packages/frontend/src/components/ui/input.tsx
  packages/frontend/src/components/ui/tag-input.tsx
  packages/frontend/src/views/theme/views/auth/sign/in/form/form-sign-in.tsx
Labels: 💡 Feature

#423 perf: Remove date-fns
  apps/backend/package.json
  apps/docs/content/docs/dev/captcha.mdx
  apps/frontend/__rest/robots.ts
  apps/frontend/__rest/sitemap.ts
  apps/frontend/next.config.ts
  apps/frontend/package.json
  package.json
  packages/backend/package.json
  packages/backend/src/plugins/core/admin/database/schema/languages.ts
  packages/create-vitnode-app/package.json
  packages/create-vitnode-app/templates/basic/apps/frontend/next.config.mjs
  packages/create-vitnode-app/templates/basic/apps/frontend/next.config.ts
  packages/create-vitnode-app/templates/create-packages-json.ts
  packages/eslint-config-typescript-vitnode/.eslintrc.react.json
  packages/eslint-config-typescript-vitnode/package.json
  packages/frontend/next.config.ts
  packages/frontend/package.json
  packages/frontend/src/components/date-format-hooks/use-date-format.ts
  packages/frontend/src/components/date-format.tsx
  packages/frontend/src/components/switchers/language-switcher.tsx
  packages/frontend/src/components/ui/calendar-picker.tsx
  packages/frontend/src/components/ui/tabs.tsx
  packages/frontend/src/hooks/use-captcha.ts
  packages/frontend/src/views/admin/views/core/langs/create-edit/fields/locale.tsx
  packages/frontend/src/views/admin/views/core/langs/create-edit/fields/locales.ts
  packages/frontend/src/views/admin/views/core/langs/create-edit/hooks/use-create-edit-lang-admin.ts
  packages/frontend/src/views/admin/views/members/users/table/filters/advanced/advanced-filters-users-members-admin.tsx
  packages/frontend/src/views/theme/layout/header/user-bar/auth.tsx
  packages/frontend/src/views/theme/views/auth/sign/up/form/form-sign-up.tsx
  packages/frontend/src/views/theme/views/auth/sign/up/sign-up-view.tsx
  packages/frontend/src/views/theme/views/profile/profile-view.tsx
  packages/frontend/src/views/theme/views/settings/nav/item/link/link-item-nav-settings.tsx
  packages/frontend/src/views/theme/views/settings/views/devices/devices-settings-view.tsx
  packages/shared/package.json
  pnpm-lock.yaml
Labels: 🚀 Performerce

#425 perf(frontend): Move admin pages to dynamic routing
  README.md
  apps/backend/package.json
  apps/docs/content/docs/dev/index.mdx
  apps/docs/package.json
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/[...slug]/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/advanced/files/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/dashboard/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/langs/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/plugins/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/settings/email/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/settings/general/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/settings/metadata/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/settings/security/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/styles/editor/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/core/styles/nav/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/members/groups/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/members/staff/administrators/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/members/staff/moderators/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/members/users/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/error.tsx
  apps/frontend/app/[locale]/admin/(auth)/layout.tsx
  apps/frontend/app/[locale]/admin/(auth)/not-found.tsx
  apps/frontend/package.json
  packages/backend/package.json
  packages/backend/src/core/languages/show/show.service.ts
  packages/backend/src/functions/pagination.ts
  packages/create-vitnode-app/package.json
  packages/create-vitnode-app/templates/create-packages-json.ts
  packages/eslint-config-typescript-vitnode/package.json
  packages/frontend/package.json
  packages/frontend/src/hooks/core/sign/up/mutation-api.ts
  packages/frontend/src/views/admin/layout/admin-layout.tsx
  packages/frontend/src/views/admin/layout/auth/auth-admin-layout.tsx
  packages/frontend/src/views/admin/views/core/advanced/files/files-advanced-core-admin-view.tsx
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/content.tsx
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/create-edit/hooks/use-create-nav-plugin-admin.ts
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/item/actions/delete/hooks/use-delete-nav-plugin-admin.ts
  packages/frontend/src/views/admin/views/install/content/steps/database/mutation-api.ts
  packages/frontend/src/views/admin/views/members/groups/groups-members-admin-view.tsx
  packages/frontend/src/views/admin/views/members/staff/administrators/administrators-view.tsx
  packages/frontend/src/views/admin/views/members/staff/moderators/moderators-view.tsx
  packages/frontend/src/views/admin/views/members/users/users-members-admin-view.tsx
  packages/frontend/src/views/admin/views/slug.tsx
  packages/frontend/src/views/layout/auth/auth-layout.tsx
  packages/shared/package.json
  pnpm-lock.yaml
Labels: 🚀 Performerce

#426 feat(frontend): Add welcome page
  .github/pull_request_template.md
  apps/backend/package.json
  apps/docs/app/global.css
  apps/docs/content/docs/dev/captcha.mdx
  apps/frontend/app/global.css
  apps/frontend/package.json
  apps/frontend/plugins/welcome/templates/default-page.tsx
  package.json
  packages/backend/package.json
  packages/backend/src/core/admin/install/create_database/create_database.service.ts
  packages/create-vitnode-app/package.json
  packages/create-vitnode-app/templates/create-packages-json.ts
  packages/eslint-config-typescript-vitnode/package.json
  packages/frontend/package.json
  packages/frontend/src/components/drag&drop-item.tsx
  packages/frontend/src/components/logo-vitnode.tsx
  packages/frontend/src/global.css
  packages/frontend/src/hooks/core/sign/out/mutation-api.ts
  packages/frontend/src/views/admin/views/core/langs/langs-core-admin-view.tsx
  packages/frontend/src/views/admin/views/theme_editor/sidebar/tabs/logos.tsx
  packages/frontend/src/views/theme/layout/header/logo.tsx
  packages/frontend/src/views/theme/layout/nav/item.tsx
  pnpm-lock.yaml
Labels: 💡 Feature
