Repository aXenDeveloper/vitnode, pull requests merged in 2024-06, with the labels that each got.

#364 refactor(frontend)!: Change dynamic icon component to server-only
  frontend/app/[locale]/(admin)/admin/(auth)/get-session-admin.ts
  frontend/app/[locale]/(admin)/admin/(auth)/layout.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/providers.tsx
  frontend/components/icon/icon-client.tsx
  frontend/components/icon/icon.tsx
  frontend/components/icon/input/content/icons/icons.tsx
  frontend/components/icon/input/icon-input.tsx
  frontend/components/ui/drawer.tsx
  frontend/functions/flatten-tree.ts
  frontend/plugins/admin/hooks/use-session-admin.ts
  frontend/plugins/admin/layout/admin-layout.tsx
  frontend/plugins/admin/layout/header/header-admin.tsx
  frontend/plugins/admin/layout/header/user-bar/user-bar-admin.tsx
  frontend/plugins/admin/layout/nav/content.tsx
  frontend/plugins/admin/layout/nav/item/item.tsx
  frontend/plugins/admin/layout/nav/item/link.tsx
  frontend/plugins/admin/layout/nav/list/item/link.tsx
  frontend/plugins/admin/layout/nav/nav-admin.tsx
  frontend/plugins/admin/views/core/plugins/views/dev/nav/item.tsx
  frontend/plugins/admin/views/core/styles/nav/nav-admin-view.tsx
  frontend/plugins/admin/views/core/styles/nav/table/item.tsx
  frontend/plugins/admin/views/core/styles/nav/table/table.tsx
  frontend/plugins/core/hooks/drag&drop/use-functions.ts
  frontend/plugins/core/hooks/drag&drop/use-projection.ts
  frontend/plugins/forum/admin/views/forums/table/hooks/use-forum-forums-admin-api.ts
  frontend/plugins/forum/admin/views/forums/table/item/item.tsx
  frontend/themes/1/core/layout/header/header.tsx
  frontend/themes/1/core/layout/nav/item.tsx
  frontend/themes/1/core/layout/nav/list-wrapper.tsx
  frontend/themes/1/core/layout/nav/nav.tsx
  frontend/themes/1/core/layout/nav/wrapper.tsx
  frontend/themes/1/core/layout/quick-menu/drawer/button.tsx
  frontend/themes/1/core/layout/quick-menu/drawer/drawer.tsx
  frontend/themes/1/core/layout/quick-menu/drawer/nav/item.tsx
  frontend/themes/1/core/layout/quick-menu/drawer/nav/nav.tsx
  frontend/themes/1/core/layout/quick-menu/quick-menu.tsx
  frontend/themes/1/core/layout/quick-menu/wrapper.tsx
  pnpm-lock.yaml
Labels: 🚀 Performerce, 🚨 Breaking Changes

#366 perf: Update TurboPack to 2.0.0 version
  .npmrc
  backend/Dockerfile
  frontend/Dockerfile
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: 🚀 Performerce

#369 feat!: Add react-compiler & partial prerendering
  backend/src/plugins/core/admin/settings/main/edit/edit.service.ts
  frontend/app/[locale]/(admin)/admin/(auth)/blog/categories/page.tsx
  frontend/components/ui/dialog.tsx
  frontend/next.config.mjs
  frontend/package.json
  frontend/plugins/admin/langs/en.json
  frontend/plugins/admin/langs/pl.json
  frontend/plugins/admin/layout/nav/nav-admin.tsx
  frontend/plugins/blog/admin/views/categories/categories-view.tsx
  frontend/plugins/blog/admin/views/categories/item/item.tsx
  frontend/plugins/blog/admin/views/categories/table/table.tsx
  frontend/plugins/core/langs/en.json
  frontend/plugins/core/langs/pl.json
  pnpm-lock.yaml
Labels: 💡 Feature, 🚨 Breaking Changes

#370 feat: Add turbopack as default compiler in dev mode
  frontend/app/[locale]/(main)/(container)/login/page.tsx
  frontend/app/[locale]/(main)/(container)/register/page.tsx
  frontend/app/[locale]/(main)/(container)/settings/devices/page.tsx
  frontend/app/[locale]/(main)/(container)/settings/files/page.tsx
  frontend/app/[locale]/(main)/(container)/settings/layout.tsx
  frontend/app/[locale]/(main)/(container)/settings/notifications/page.tsx
  frontend/app/[locale]/(main)/(container)/settings/page.tsx
  frontend/app/[locale]/(main)/layout.tsx
  frontend/app/[locale]/(main)/page.tsx
  frontend/app/[locale]/(main)/profile/[id]/page.tsx
  frontend/app/[locale]/catch.tsx
  frontend/app/[locale]/layout.tsx
  frontend/components/ui/table.tsx
  frontend/components/views/error-view-ssr.tsx
  frontend/i18n.ts
  frontend/package.json
  frontend/plugins/blog/admin/views/categories/categories-view.tsx
  frontend/plugins/blog/admin/views/categories/create-edit/hooks/create-mutation-api.ts
Labels: 💡 Feature

#371 feat(email): Add config email SMTP in AdminCP
  backend/package.json
  backend/schema.gql
  backend/src/plugins/core/admin/admin.module.ts
  backend/src/plugins/core/admin/email/.gitignore
  backend/src/plugins/core/admin/email/email.module.ts
  backend/src/plugins/core/admin/email/helpers.service.ts
  backend/src/plugins/core/admin/email/send/dto/send.args.ts
  backend/src/plugins/core/admin/email/send/send.service.ts
  backend/src/plugins/core/admin/email/settings/edit/dto/edit.args.ts
  backend/src/plugins/core/admin/email/settings/edit/edit.resolver.ts
  backend/src/plugins/core/admin/email/settings/edit/edit.service.ts
  backend/src/plugins/core/admin/email/settings/show/dto/show.obj.ts
  backend/src/plugins/core/admin/email/settings/show/show.resolver.ts
  backend/src/plugins/core/admin/email/settings/show/show.service.ts
  backend/src/plugins/core/admin/email/settings/test/test.resolver.ts
  backend/src/plugins/core/admin/email/settings/test/test.service.ts
  backend/src/plugins/core/core.module.ts
  backend/src/plugins/core/mail/mail.module.ts
  backend/src/plugins/core/mail/send/dto/mail.args.ts
  backend/src/plugins/core/mail/send/mail.resolver.ts
  backend/src/plugins/core/mail/send/mail.service.ts
  frontend/app/[locale]/(admin)/admin/(auth)/core/settings/email/page.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/dialog.tsx
  frontend/components/ui/form.tsx
  frontend/next.config.mjs
  frontend/package.json
  frontend/plugins/admin/graphql/mutations/settings/admin__core_manifest_metadata__edit.gql
  frontend/plugins/admin/graphql/mutations/settings/email/admin__core_email_settings__edit.gql
  frontend/plugins/admin/graphql/mutations/settings/email/admin__core_email_settings__test.gql
  frontend/plugins/admin/graphql/queries/settings/admin__core_email_settings__show.gql
  frontend/plugins/admin/graphql/queries/settings/admin__core_manifest_metadata__show.gql
  frontend/plugins/admin/langs/en.json
  frontend/plugins/admin/langs/pl.json
  frontend/plugins/admin/layout/nav/item/link.tsx
  frontend/plugins/admin/layout/nav/nav-admin.tsx
  frontend/plugins/admin/views/core/settings/email/actions/actions.tsx
  frontend/plugins/admin/views/core/settings/email/actions/testing/content.tsx
  frontend/plugins/admin/views/core/settings/email/actions/testing/hooks/mutation-api.ts
  frontend/plugins/admin/views/core/settings/email/actions/testing/hooks/use-testing-email-admin.ts
  frontend/plugins/admin/views/core/settings/email/actions/testing/testing.tsx
  frontend/plugins/admin/views/core/settings/email/email-settings-admin-view.tsx
  frontend/plugins/admin/views/core/settings/email/hooks/mutation-api.ts
  frontend/plugins/admin/views/core/settings/email/hooks/use-email-settings-form-admin.ts
  frontend/plugins/admin/views/core/styles/editor/sections/files.tsx
  frontend/plugins/core/langs/en.json
  frontend/plugins/core/langs/pl.json
  frontend/utils/graphql/hooks.ts
  package.json
  pnpm-lock.yaml
Labels: 💡 Feature

#373 feat: Delete user
  backend/schema.gql
  backend/src/plugins/core/members/delete/delete.resolver.ts
  backend/src/plugins/core/members/delete/delete.service.ts
  backend/src/plugins/core/members/delete/dto/delete.args.ts
  backend/src/plugins/core/members/members.module.ts
Labels: 💡 Feature

#377 fix(mail): Create empty config mail when doesn't exists
  backend/src/plugins/core/admin/email/mail.service.ts
  backend/src/plugins/core/admin/email/settings/show/show.service.ts
Labels: 🐞 Bug

#379 feat: Edit users
  backend/schema.gql
  backend/src/plugins/core/admin/members/edit/dto/edit.args.ts
  backend/src/plugins/core/admin/members/edit/dto/edit.obj.ts
  backend/src/plugins/core/admin/members/edit/edit.resolver.ts
  backend/src/plugins/core/admin/members/edit/edit.service.ts
  backend/src/plugins/core/admin/members/members.module.ts
  backend/src/plugins/core/members/delete/delete.service.ts
Labels: 💡 Feature

#383 refactor: Change install page to client component, remove url state
  backend/src/plugins/core/admin/install/layout/layout.service.ts
  frontend/app/[locale]/(admin)/admin/(configs)/install/account/page.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/database/page.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/error.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/layout.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/license/page.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/page.tsx
  frontend/components/steps/steps.tsx
  frontend/plugins/admin/configs/views/install/finish/finish-install-config-view.tsx
  frontend/plugins/admin/configs/views/install/hooks/use-install-vitnode.ts
  frontend/plugins/admin/configs/views/install/layout-install-configs-view.tsx
  frontend/plugins/admin/configs/views/install/redirects-install-configs-layout.tsx
  frontend/plugins/admin/configs/views/install/steps/account/account-install-configs-view.tsx
  frontend/plugins/admin/configs/views/install/steps/database/database-install-configs-view.tsx
  frontend/plugins/admin/configs/views/install/steps/database/mutation-api.ts
  frontend/plugins/admin/configs/views/install/steps/database/submit-database-install-configs.tsx
  frontend/plugins/admin/configs/views/install/steps/install-configs-view.tsx
  frontend/plugins/admin/configs/views/install/steps/license/form-license-install-configs.tsx
  frontend/plugins/admin/configs/views/install/steps/license/license-install-configs-view.tsx
  frontend/plugins/admin/langs/en.json
  frontend/plugins/admin/langs/pl.json
  frontend/plugins/core/langs/en.json
  frontend/plugins/core/langs/pl.json
  frontend/themes/1/core/views/auth/sign/up/form/form-sign-up.tsx
Labels: 🚀 Performerce

#381 feat(blog): Add permissions table in AdminCP for blog plugin
  backend/drizzle.config.ts
  backend/schema.gql
  backend/src/plugins/blog/admin/categories/create/create.service.ts
  backend/src/plugins/blog/admin/categories/create/dto/create.args.ts
  backend/src/plugins/blog/admin/database/migrations/0000_tranquil_cammi.sql
  backend/src/plugins/blog/admin/database/migrations/0001_material_echo.sql
  backend/src/plugins/blog/admin/database/migrations/meta/0000_snapshot.json
  backend/src/plugins/blog/admin/database/migrations/meta/0001_snapshot.json
  backend/src/plugins/blog/admin/database/migrations/meta/_journal.json
  backend/src/plugins/blog/admin/database/schema/categories.ts
  backend/src/plugins/core/admin/database/migrations/0000_yielding_bloodstrike.sql
  backend/src/plugins/core/admin/database/migrations/0001_married_big_bertha.sql
  backend/src/plugins/core/admin/database/migrations/meta/0000_snapshot.json
  backend/src/plugins/core/admin/database/migrations/meta/0001_snapshot.json
  backend/src/plugins/core/admin/database/migrations/meta/_journal.json
  frontend/app/[locale]/(admin)/admin/(configs)/install/account/page.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/database/page.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/error.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/layout.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/license/page.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/page.tsx
  frontend/components/color/color-input.tsx
  frontend/components/permissions-table/permissions-table.tsx
  frontend/components/permissions-table/query-api.ts
  frontend/components/permissions-table/use-permissions-table-api.ts
  frontend/components/steps/steps.tsx
  frontend/components/tabs/tabs-trigger.tsx
  frontend/components/tabs/tabs.tsx
  frontend/components/ui/dialog.tsx
  frontend/graphql/hooks.ts
  frontend/plugins/admin/configs/views/install/finish/finish-install-config-view.tsx
  frontend/plugins/admin/configs/views/install/hooks/use-install-vitnode.ts
  frontend/plugins/admin/configs/views/install/layout-install-configs-view.tsx
  frontend/plugins/admin/configs/views/install/redirects-install-configs-layout.tsx
  frontend/plugins/admin/configs/views/install/steps/account/account-install-configs-view.tsx
  frontend/plugins/admin/configs/views/install/steps/database/database-install-configs-view.tsx
  frontend/plugins/admin/configs/views/install/steps/database/mutation-api.ts
  frontend/plugins/admin/configs/views/install/steps/database/submit-database-install-configs.tsx
  frontend/plugins/admin/configs/views/install/steps/install-configs-view.tsx
  frontend/plugins/admin/configs/views/install/steps/license/form-license-install-configs.tsx
  frontend/plugins/admin/configs/views/install/steps/license/license-install-configs-view.tsx
  frontend/plugins/admin/langs/en.json
  frontend/plugins/admin/langs/pl.json
  frontend/plugins/blog/admin/views/categories/create-edit/create-edit.tsx
  frontend/plugins/blog/admin/views/categories/create-edit/hooks/use-create-edit-category-blog-admin.ts
  frontend/plugins/blog/admin/views/categories/create-edit/tabs/main.tsx
  frontend/plugins/blog/admin/views/categories/create-edit/tabs/permissions.tsx
  frontend/plugins/blog/graphql/mutations/admin/categories/admin__blog_categories__create.gql
  frontend/plugins/blog/langs/en.json
  frontend/plugins/blog/langs/pl.json
  frontend/plugins/core/langs/en.json
  frontend/plugins/core/langs/pl.json
  frontend/themes/1/core/views/auth/sign/up/form/form-sign-up.tsx
  packages/eslint-config-vitnode/.eslintrc.json
Labels: 💡 Feature

#382 feat: Decorator for checking if admin has a specific permissions
  backend/src/plugins/core/admin/database/schema/admins.ts
  backend/src/plugins/core/admin/groups/create/create.resolver.ts
  backend/src/utils/guards/admin-permission.guard.ts
Labels: 💡 Feature
