Repository aXenDeveloper/vitnode, pull requests merged in 2024-08, with the labels that each got.

#430 perf!: Remove versions.json, move version to config.json
  apps/backend/schema.gql
  apps/backend/src/plugins/welcome/config.json
  apps/backend/src/plugins/welcome/versions.json
  apps/docs/assets/ui/plugins/form-create-plugin.png
  apps/docs/content/docs/dev/index.mdx
  apps/docs/content/docs/dev/meta.json
  apps/docs/content/docs/dev/plugins.mdx
  apps/docs/content/docs/dev/rate-limiting.mdx
  packages/backend/scripts/update-plugins.ts
  packages/backend/src/app.module.ts
  packages/backend/src/core/admin/files/download/download.controller.ts
  packages/backend/src/core/admin/plugins/create/create.service.ts
  packages/backend/src/core/admin/plugins/download/download.service.ts
  packages/backend/src/core/admin/plugins/helpers/files/create/create-files.service.ts
  packages/backend/src/core/admin/plugins/show/dto/show.obj.ts
  packages/backend/src/core/admin/plugins/upload/upload.service.ts
  packages/backend/src/core/admin/settings/functions/get-core-info.ts
  packages/backend/src/core/files/download/download.controller.ts
  packages/backend/src/database/schema/plugins.ts
  packages/backend/src/providers/plugins.type.ts
  packages/create-vitnode-app/templates/basic/apps/backend/src/plugins/welcome/config.json
  packages/create-vitnode-app/templates/basic/apps/backend/src/plugins/welcome/versions.json
Labels: 🚀 Performerce, 🚨 Breaking Changes

#432 feat(cli): Add init git
  apps/backend/package.json
  apps/docs/package.json
  apps/frontend/package.json
  packages/backend/package.json
  packages/create-vitnode-app/helpers/git.ts
  packages/create-vitnode-app/package.json
  packages/create-vitnode-app/templates/basic/apps/frontend/app/global.css
  packages/create-vitnode-app/templates/create-packages-json.ts
  packages/create-vitnode-app/templates/create-vitnode.ts
  packages/eslint-config-typescript-vitnode/package.json
  packages/frontend/package.json
  packages/shared/package.json
Labels: 💡 Feature

#433 feat(cli): Add generator for .env file
  __old_docs/pages/docs/deployment/install.mdx
  packages/backend/src/core/sessions/authorization/internal/internal_authorization.service.ts
  packages/backend/src/core/sessions/sign_in/sign_in.service.ts
  packages/create-vitnode-app/helpers/create-packages-json.ts
  packages/create-vitnode-app/helpers/install-dependencies.ts
  packages/create-vitnode-app/templates/basic/.env_template
  packages/create-vitnode-app/templates/create-vitnode.ts
Labels: 💡 Feature

#434 perf(shared)!: Remove shared package
  .github/workflows/publish.yaml
  apps/backend/package.json
  apps/docs/content/docs/dev/functions.mdx
  apps/frontend/package.json
  packages/backend/package.json
  packages/backend/src/core/admin/languages/download/download.service.ts
  packages/backend/src/core/admin/languages/update/update.service.ts
  packages/backend/src/core/admin/plugins/download/download.service.ts
  packages/backend/src/core/admin/plugins/nav/create/create.service.ts
  packages/backend/src/core/admin/plugins/nav/edit/edit.service.ts
  packages/backend/src/core/admin/plugins/upload/upload.service.ts
  packages/backend/src/core/editor/upload/upload.service.ts
  packages/backend/src/core/files/helpers/upload/upload.service.ts
  packages/backend/src/core/members/reset_password/create_key/create_key.service.ts
  packages/backend/src/core/sessions/sign_up/helpers/avatar-color.service.ts
  packages/backend/src/core/sessions/sign_up/sign_up.service.ts
  packages/backend/src/functions/colors.ts
  packages/backend/src/functions/generate-random-string.ts
  packages/backend/src/functions/index.ts
  packages/backend/src/functions/special-characters.ts
  packages/backend/src/providers/email/email-helpers.service.ts
  packages/create-vitnode-app/templates/create-vitnode.ts
  packages/frontend/next.config.ts
  packages/frontend/package.json
  packages/frontend/src/components/ui/color-picker.tsx
  packages/frontend/src/components/ui/picker-color.tsx
  packages/frontend/src/editor/extensions/files/client.tsx
  packages/frontend/src/editor/extensions/files/hooks/use-upload-files-handler-editor.ts.ts
  packages/frontend/src/editor/footer/files/item/content.tsx
  packages/frontend/src/editor/read-only/code-block.tsx
  packages/frontend/src/editor/read-only/file-download-button.tsx
  packages/frontend/src/editor/toolbar/custom/color/color.tsx
  packages/frontend/src/helpers/colors.ts
  packages/frontend/src/helpers/format-bytes.ts
  packages/frontend/src/helpers/generate-random-string.ts
  packages/frontend/src/helpers/special-characters.ts
  packages/frontend/src/hooks/use-text-lang.ts
  packages/frontend/src/url.ts
  packages/frontend/src/views/admin/views/core/advanced/files/content.tsx
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/create-edit/create-edit.tsx
  packages/frontend/src/views/admin/views/core/settings/email/hooks/use-email-settings-form-admin.ts
  packages/frontend/src/views/admin/views/core/settings/metadata/manifest/hooks/use-manifest-core-admin-view.ts
  packages/frontend/src/views/admin/views/install/content/steps/account/account-install-configs-view.tsx
  packages/frontend/src/views/admin/views/theme_editor/sidebar/tabs/color.tsx
  packages/frontend/src/views/theme/views/auth/sign/up/form/form-sign-up.tsx
  packages/frontend/src/views/theme/views/settings/views/files/content.tsx
  packages/shared/.eslintrc.json
  packages/shared/.npmignore
  packages/shared/README.md
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/tsconfig.json
  pnpm-lock.yaml
Labels: 🚀 Performerce, 🚨 Breaking Changes

#435 refactor(frontend): Remove react-colorful
  packages/frontend/package.json
  packages/frontend/src/components/ui/color-picker.tsx
  packages/frontend/src/components/ui/picker-color.tsx
  packages/frontend/src/editor/toolbar/custom/color/color.tsx
  packages/frontend/src/views/admin/views/theme_editor/hooks/use-theme-editor-api.ts
  packages/frontend/src/views/admin/views/theme_editor/hooks/use-theme-editor.ts
  pnpm-lock.yaml
Labels: 🧱 Refactor

#436 fix(backend): Invalid convert color when user is sing up
  packages/backend/src/core/sessions/sign_up/helpers/avatar-color.service.ts
  packages/backend/src/core/sessions/sign_up/sign_up.service.ts
  packages/backend/src/functions/colors.ts
  packages/frontend/src/helpers/colors.ts
  packages/frontend/src/hooks/core/sign/up/use-sign-up-view.ts
Labels: 🐞 Bug

#437 feat: Add support for resend email
  apps/backend/package.json
  apps/backend/schema.gql
  apps/docs/package.json
  apps/frontend/package.json
  apps/frontend/plugins/admin/langs/en.json
  packages/backend/package.json
  packages/backend/src/core/admin/email/helpers.service.ts
  packages/backend/src/core/admin/email/mail.service.ts
  packages/backend/src/core/admin/email/settings/edit/dto/edit.args.ts
  packages/backend/src/core/admin/email/settings/edit/edit.service.ts
  packages/backend/src/core/admin/email/settings/show/dto/show.obj.ts
  packages/backend/src/core/admin/email/settings/show/show.service.ts
  packages/backend/src/providers/config.ts
  packages/create-vitnode-app/helpers/create-packages-json.ts
  packages/create-vitnode-app/package.json
  packages/frontend/package.json
  packages/frontend/src/components/ui/color-picker.tsx
  packages/frontend/src/components/ui/radio-group.tsx
  packages/frontend/src/graphql/mutations/admin/settings/email/admin__core_email_settings__edit.generated.ts
  packages/frontend/src/graphql/mutations/admin/settings/email/admin__core_email_settings__edit.gql
  packages/frontend/src/graphql/queries/admin/admin__sessions__authorization.generated.ts
  packages/frontend/src/graphql/queries/admin/groups/admin__core_groups__show_short.generated.ts
  packages/frontend/src/graphql/queries/admin/members/groups/admin__core_groups__show.generated.ts
  packages/frontend/src/graphql/queries/admin/members/staff/admin__core_staff_administrators__show.generated.ts
  packages/frontend/src/graphql/queries/admin/members/staff/admin__core_staff_moderators__show.generated.ts
  packages/frontend/src/graphql/queries/admin/members/users/admin__core_members__show.generated.ts
  packages/frontend/src/graphql/queries/admin/settings/admin__core_email_settings__show.generated.ts
  packages/frontend/src/graphql/queries/admin/settings/admin__core_email_settings__show.gql
  packages/frontend/src/graphql/queries/core_sessions__authorization.generated.ts
  packages/frontend/src/graphql/queries/profiles/core_members__profiles.generated.ts
  packages/frontend/src/graphql/queries/users/core_members__show__search.generated.ts
  packages/frontend/src/graphql/types.ts
  packages/frontend/src/views/admin/views/core/settings/email/actions/actions.tsx
  packages/frontend/src/views/admin/views/core/settings/email/actions/testing/testing.tsx
  packages/frontend/src/views/admin/views/core/settings/email/content.tsx
  packages/frontend/src/views/admin/views/core/settings/email/email-settings-admin-view.tsx
  packages/frontend/src/views/admin/views/core/settings/email/hooks/use-email-settings-form-admin.ts
  pnpm-lock.yaml
Labels: 💡 Feature

#439 refactor!: Files upload system
  apps/backend/schema.gql
  apps/docs/content/docs/dev/files.mdx
  apps/docs/content/docs/ui/forms/file-input.mdx
  packages/backend/src/core/admin/email/settings/edit/dto/edit.args.ts
  packages/backend/src/core/admin/theme_editor/edit/dto/edit.args.ts
  packages/backend/src/core/files/helpers/upload/dto/delete.args.ts
  packages/backend/src/core/files/helpers/upload/dto/upload.args.ts
  packages/backend/src/core/files/helpers/upload/dto/upload.obj.ts
  packages/frontend/src/components/ui/file-input.tsx
  packages/frontend/src/components/utils/files/item-preview-files-input.tsx
  packages/frontend/src/components/utils/files/preview-files-input.tsx
  packages/frontend/src/helpers/zod.ts
  packages/frontend/src/views/admin/views/core/langs/table/actions/update/content.tsx
  packages/frontend/src/views/admin/views/core/langs/table/actions/update/hooks/use-update-lang-admin.ts
  packages/frontend/src/views/admin/views/core/plugins/upload/hooks/use-upload-plugin-admin.ts
  packages/frontend/src/views/admin/views/core/plugins/upload/upload.tsx
  packages/frontend/src/views/admin/views/core/settings/email/hooks/use-email-settings-form-admin.ts
  packages/frontend/src/views/admin/views/theme_editor/hooks/use-theme-editor-api.ts
  packages/frontend/src/views/admin/views/theme_editor/hooks/use-theme-editor.ts
  packages/frontend/src/views/admin/views/theme_editor/sidebar/tabs/logos.tsx
  packages/frontend/src/views/theme/views/settings/views/overview/header/change-avatar/modal/hooks/use-modal-change-avatar.ts
  packages/frontend/src/views/theme/views/settings/views/overview/header/change-avatar/modal/modal-change-avatar.tsx
Labels: 🧱 Refactor, 🚨 Breaking Changes

#438 feat: Add logo for email
  apps/backend/schema.gql
  apps/docs/content/docs/dev/files.mdx
  apps/docs/content/docs/ui/forms/file-input.mdx
  apps/frontend/plugins/admin/langs/en.json
  packages/backend/src/app.module.ts
  packages/backend/src/core/admin/email/helpers.service.ts
  packages/backend/src/core/admin/email/settings/edit/dto/edit.args.ts
  packages/backend/src/core/admin/email/settings/edit/edit.resolver.ts
  packages/backend/src/core/admin/email/settings/edit/edit.service.ts
  packages/backend/src/core/admin/email/settings/show/dto/show.obj.ts
  packages/backend/src/core/admin/files/delete/delete.service.ts
  packages/backend/src/core/admin/theme_editor/edit/dto/edit.args.ts
  packages/backend/src/core/admin/theme_editor/edit/edit.service.ts
  packages/backend/src/core/editor/delete/delete.service.ts
  packages/backend/src/core/editor/upload/upload.service.ts
  packages/backend/src/core/files/files.cron.ts
  packages/backend/src/core/files/files.module.ts
  packages/backend/src/core/files/helpers/delete/delete.service.ts
  packages/backend/src/core/files/helpers/delete/dto/delete.args.ts
  packages/backend/src/core/files/helpers/upload/dto/delete.args.ts
  packages/backend/src/core/files/helpers/upload/dto/upload.args.ts
  packages/backend/src/core/files/helpers/upload/upload.service.ts
  packages/backend/src/core/members/avatar/delete/delete.service.ts
  packages/backend/src/core/members/avatar/upload/upload.service.ts
  packages/backend/src/providers/config.ts
  packages/backend/src/providers/email/email-helpers.service.ts
  packages/backend/src/providers/email/email-helpers.type.ts
  packages/backend/src/providers/email/template/email-template.tsx
  packages/frontend/src/components/ui/file-input.tsx
  packages/frontend/src/components/ui/permissions-table.tsx
  packages/frontend/src/components/ui/user/group-input.tsx
  packages/frontend/src/components/ui/user/user-input.tsx
  packages/frontend/src/components/utils/files/item-preview-files-input.tsx
  packages/frontend/src/components/utils/files/preview-files-input.tsx
  packages/frontend/src/components/utils/permissions-table/use-permissions-table-api.ts
  packages/frontend/src/components/utils/user/group-input/content.tsx
  packages/frontend/src/components/utils/user/group-input/list.tsx
  packages/frontend/src/components/utils/user/user-input/content.tsx
  packages/frontend/src/components/utils/user/user-input/list.tsx
  packages/frontend/src/graphql/mutations/admin/settings/email/admin__core_email_settings__edit.generated.ts
  packages/frontend/src/graphql/mutations/admin/settings/email/admin__core_email_settings__edit.gql
  packages/frontend/src/graphql/queries/admin/settings/admin__core_email_settings__show.generated.ts
  packages/frontend/src/graphql/queries/admin/settings/admin__core_email_settings__show.gql
  packages/frontend/src/graphql/types.ts
  packages/frontend/src/helpers/zod.ts
  packages/frontend/src/utils/components/files/preview-files-input.tsx
  packages/frontend/src/views/admin/views/core/langs/table/actions/update/content.tsx
  packages/frontend/src/views/admin/views/core/langs/table/actions/update/hooks/use-update-lang-admin.ts
  packages/frontend/src/views/admin/views/core/plugins/upload/hooks/use-upload-plugin-admin.ts
  packages/frontend/src/views/admin/views/core/plugins/upload/upload.tsx
  packages/frontend/src/views/admin/views/core/settings/email/actions/testing/testing.tsx
  packages/frontend/src/views/admin/views/core/settings/email/content.tsx
  packages/frontend/src/views/admin/views/core/settings/email/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/settings/email/hooks/use-email-settings-form-admin.ts
  packages/frontend/src/views/admin/views/theme_editor/hooks/use-theme-editor-api.ts
  packages/frontend/src/views/admin/views/theme_editor/hooks/use-theme-editor.ts
  packages/frontend/src/views/admin/views/theme_editor/sidebar/tabs/logos.tsx
  packages/frontend/src/views/theme/views/settings/views/overview/header/change-avatar/modal/hooks/use-modal-change-avatar.ts
  packages/frontend/src/views/theme/views/settings/views/overview/header/change-avatar/modal/modal-change-avatar.tsx
Labels: 💡 Feature

#441 fix(backend): Trim string when is optional for TransformString
  packages/backend/src/utils/text-language.ts
Labels: 🐞 Bug

#446 fix(frontend): Invalid path for Auto Form
  apps/docs/content/docs/dev/lint.mdx
  apps/docs/content/docs/dev/meta.json
  apps/docs/content/docs/dev/pages.mdx
  apps/docs/content/docs/ui/forms/auto-form.mdx
  apps/docs/content/docs/ui/forms/checkbox.mdx
  apps/docs/content/docs/ui/forms/color-picker.mdx
  apps/docs/content/docs/ui/forms/combobox.mdx
  apps/docs/content/docs/ui/forms/file-input.mdx
  apps/docs/content/docs/ui/forms/icon-picker.mdx
  apps/docs/content/docs/ui/forms/input.mdx
  apps/docs/content/docs/ui/forms/radio-group.mdx
  apps/docs/content/docs/ui/forms/select.mdx
  apps/docs/content/docs/ui/forms/switch.mdx
  apps/docs/content/docs/ui/forms/tags-input.mdx
  apps/docs/content/docs/ui/forms/text-language-input.mdx
  apps/docs/content/docs/ui/forms/textarea.mdx
  packages/frontend/src/components/form/auto-form.tsx
  packages/frontend/src/components/form/fields/checkbox.tsx
  packages/frontend/src/components/form/fields/color.tsx
  packages/frontend/src/components/form/fields/combobox.tsx
  packages/frontend/src/components/form/fields/common/children.tsx
  packages/frontend/src/components/form/fields/common/label.tsx
  packages/frontend/src/components/form/fields/common/tooltip.tsx
  packages/frontend/src/components/form/fields/common/wrapper.tsx
  packages/frontend/src/components/form/fields/file.tsx
  packages/frontend/src/components/form/fields/icon.tsx
  packages/frontend/src/components/form/fields/input.tsx
  packages/frontend/src/components/form/fields/radio-group.tsx
  packages/frontend/src/components/form/fields/select.tsx
  packages/frontend/src/components/form/fields/switch.tsx
  packages/frontend/src/components/form/fields/tags.tsx
  packages/frontend/src/components/form/fields/text-language-input.tsx
  packages/frontend/src/components/form/fields/textarea.tsx
  packages/frontend/src/components/form/object.tsx
  packages/frontend/src/components/form/type.ts
  packages/frontend/src/components/form/utils.ts
  packages/frontend/src/views/admin/views/core/langs/create-edit/create-edit.tsx
  packages/frontend/src/views/admin/views/core/langs/table/actions/delete/content.tsx
  packages/frontend/src/views/admin/views/core/langs/table/actions/download/content.tsx
  packages/frontend/src/views/admin/views/core/langs/table/actions/update/content.tsx
  packages/frontend/src/views/admin/views/core/plugins/actions/create/form.tsx
  packages/frontend/src/views/admin/views/core/plugins/upload/upload.tsx
  packages/frontend/src/views/admin/views/core/plugins/views/dev/layout/actions/download/content.tsx
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/create-edit/create-edit.tsx
  packages/frontend/src/views/admin/views/core/settings/email/actions/testing/content.tsx
  packages/frontend/src/views/admin/views/core/settings/email/content.tsx
  packages/frontend/src/views/admin/views/core/settings/main/content.tsx
  packages/frontend/src/views/admin/views/core/settings/metadata/manifest/content.tsx
  packages/frontend/src/views/admin/views/core/settings/security/captcha/content.tsx
  packages/frontend/src/views/admin/views/core/styles/editor/content.tsx
  packages/frontend/src/views/admin/views/core/styles/nav/create-edit/create-edit.tsx
  packages/frontend/src/views/admin/views/install/content/steps/account/account-install-configs-view.tsx
  packages/frontend/src/views/admin/views/install/content/steps/license/form-license-install-configs.tsx
  packages/frontend/src/views/admin/views/members/groups/create-edit-form/create-edit-form-groups-members-admin.tsx
  packages/frontend/src/views/admin/views/members/groups/table/actions/delete/content.tsx
  packages/frontend/src/views/admin/views/sign-in/form-sign-in-admin.tsx
  packages/frontend/src/views/theme/views/auth/sign/in/form/form-sign-in.tsx
  packages/frontend/src/views/theme/views/auth/sign/up/form/form-sign-up.tsx
Labels: 🐞 Bug

#447 feat(cli): Add database generate using cli
  __old_docs/pages/docs/plugins/database/overview.mdx
  apps/backend/package.json
  apps/docs/content/docs/dev/database.mdx
  apps/docs/content/docs/dev/lint.mdx
  apps/docs/content/docs/dev/meta.json
  package.json
  packages/backend/scripts/setup.ts
  packages/create-vitnode-app/helpers/create-packages-json.ts
  packages/create-vitnode-app/templates/basic/turbo.json
  turbo.json
Labels: 💡 Feature

#449 feat(frontend): Add diagnostic tools view in AdminCP
  apps/docs/content/docs/guides/diagnostic.mdx
  apps/docs/content/docs/ui/alert-dialog.mdx
  apps/docs/content/docs/ui/dialog.mdx
  apps/frontend/package.json
  apps/frontend/plugins/admin/langs/en.json
  packages/backend/scripts/update-plugins.ts
  packages/backend/src/core/admin/plugins/delete/delete.service.ts
  packages/backend/src/database/schema/files.ts
  packages/create-vitnode-app/helpers/create-packages-json.ts
  packages/frontend/src/views/admin/layout/auth/aside/avatar.tsx
  packages/frontend/src/views/admin/views/core/diagnostic/actions/actions.tsx
  packages/frontend/src/views/admin/views/core/diagnostic/actions/clear_cache/clear_cache.tsx
  packages/frontend/src/views/admin/views/core/diagnostic/actions/clear_cache/content.tsx
  packages/frontend/src/views/admin/views/core/diagnostic/actions/clear_cache/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/diagnostic/diagnostic-tools-view.tsx
  packages/frontend/src/views/admin/views/slug.tsx
Labels: 💡 Feature

#450 perf: Add change global.d.ts file when create / delete plugin
  apps/backend/src/database/config.ts
  apps/backend/src/main.ts
  apps/frontend/global.d.ts
  apps/frontend/package.json
  packages/backend/src/core/admin/plugins/delete/contents.ts
  packages/backend/src/core/admin/plugins/helpers/files/change/contents.ts
  packages/create-vitnode-app/helpers/create-packages-json.ts
  packages/create-vitnode-app/templates/basic/apps/frontend/global.d.ts
Labels: 🚀 Performerce

#452 perf(frontend)!: Remove search param in getPaginationTool
  __old_docs/pages/docs/plugins/database/search.mdx
  apps/docs/content/docs/dev/codegen.mdx
  apps/docs/content/docs/dev/database-filters.mdx
  apps/docs/content/docs/dev/database.mdx
  apps/docs/content/docs/dev/lint.mdx
  apps/docs/content/docs/dev/meta.json
  apps/docs/content/docs/dev/plugins.mdx
  apps/docs/content/docs/ui/data-table.mdx
  packages/eslint-config-typescript-vitnode/.eslintrc.react.json
  packages/frontend/src/components/ui/data-table.tsx
  packages/frontend/src/graphql/get-pagination-tool.ts
  packages/frontend/src/views/admin/views/core/advanced/files/files-advanced-core-admin-view.tsx
  packages/frontend/src/views/admin/views/core/langs/langs-core-admin-view.tsx
  packages/frontend/src/views/admin/views/core/plugins/plugins-admin-view.tsx
  packages/frontend/src/views/admin/views/members/groups/groups-members-admin-view.tsx
  packages/frontend/src/views/admin/views/members/staff/administrators/administrators-view.tsx
  packages/frontend/src/views/admin/views/members/staff/moderators/moderators-view.tsx
  packages/frontend/src/views/admin/views/members/users/users-members-admin-view.tsx
  packages/frontend/src/views/theme/views/settings/views/files/files-settings-view.tsx
Labels: 🚀 Performerce, 🚨 Breaking Changes

#453 feat(frontend): Add date picker
  apps/backend/src/main.ts
  apps/docs/assets/ui/components/checkbox.png
  apps/docs/assets/ui/components/color-picker.png
  apps/docs/assets/ui/components/combobox.png
  apps/docs/assets/ui/components/date-picker.png
  apps/docs/assets/ui/components/input.png
  apps/docs/assets/ui/components/radio-group.png
  apps/docs/assets/ui/components/select.png
  apps/docs/assets/ui/components/switch.png
  apps/docs/assets/ui/components/tags-input.png
  apps/docs/assets/ui/components/text-language-input.png
  apps/docs/assets/ui/components/textarea.png
  apps/docs/content/docs/ui/calendar.mdx
  apps/docs/content/docs/ui/forms/auto-form.mdx
  apps/docs/content/docs/ui/forms/checkbox.mdx
  apps/docs/content/docs/ui/forms/color-picker.mdx
  apps/docs/content/docs/ui/forms/combobox.mdx
  apps/docs/content/docs/ui/forms/date-picker.mdx
  apps/docs/content/docs/ui/forms/input.mdx
  apps/docs/content/docs/ui/forms/radio-group.mdx
  apps/docs/content/docs/ui/forms/select.mdx
  apps/docs/content/docs/ui/forms/switch.mdx
  apps/docs/content/docs/ui/forms/tags-input.mdx
  apps/docs/content/docs/ui/forms/text-language-input.mdx
  apps/docs/content/docs/ui/forms/textarea.mdx
  apps/docs/content/docs/ui/scroll-area.mdx
  apps/frontend/plugins/core/langs/en.json
  packages/frontend/src/components/form/fields/date.tsx
  packages/frontend/src/components/form/fields/switch.tsx
  packages/frontend/src/components/ui/calendar.tsx
  packages/frontend/src/components/ui/data-table.tsx
  packages/frontend/src/components/ui/date-picker.tsx
  packages/frontend/src/components/ui/scroll-area.tsx
Labels: 💡 Feature

#454 refactor(frontend): Tabs color
  apps/docs/app/global.css
  apps/frontend/app/[locale]/global.css
  apps/frontend/app/[locale]/layout.tsx
  apps/frontend/app/layout.tsx
  apps/frontend/plugins/welcome/templates/default-page.tsx
  packages/backend/src/core/admin/theme_editor/edit/edit.service.ts
  packages/backend/src/core/theme_editor/show/show.service.ts
  packages/backend/src/providers/config.ts
  packages/create-vitnode-app/templates/basic/apps/frontend/app/[locale]/global.css
  packages/create-vitnode-app/templates/basic/apps/frontend/app/[locale]/layout.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/app/layout.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/plugins/welcome/templates/default-page.tsx
  packages/frontend/package.json
  packages/frontend/src/components/icon/icon.tsx
  packages/frontend/src/components/ui/file-input.tsx
  packages/frontend/src/components/ui/tabs.tsx
  packages/frontend/src/global.css
  packages/frontend/src/views/admin/views/sign-in/sign-in-admin-view.tsx
  packages/frontend/src/views/global/internal-error/internal-error-view.tsx
  packages/frontend/src/views/global/powered-by.tsx
  packages/frontend/src/views/layout/root-layout.tsx
  packages/frontend/src/views/layout/wrapper.tsx
  packages/frontend/src/views/theme/layout/footer.tsx
  packages/frontend/src/views/theme/layout/header/logo.tsx
  packages/frontend/src/views/theme/layout/nav/hooks/use-nav.ts
  packages/frontend/src/views/theme/layout/nav/item.tsx
  packages/frontend/src/views/theme/layout/nav/list-wrapper.tsx
  packages/frontend/src/views/theme/layout/nav/nav.tsx
  packages/frontend/src/views/theme/layout/nav/wrapper.tsx
  packages/frontend/src/views/theme/layout/quick-menu/drawer/nav/nav.tsx
  packages/frontend/src/views/theme/layout/quick-menu/wrapper.tsx
  packages/frontend/src/views/theme/views/settings/nav/item/link/link-item-nav-settings.tsx
  packages/frontend/src/views/theme/views/settings/nav/nav-settings.tsx
  pnpm-lock.yaml
Labels: 🧱 Refactor

#455 fix(frontend): Display not found page inside main and admin folder
  .github/workflows/build.yml
  apps/docs/app/global.css
  apps/docs/content/docs/dev/fetch.mdx
  apps/docs/content/docs/ui/forms/auto-form.mdx
  apps/docs/content/docs/ui/meta.json
  apps/docs/content/docs/ui/navigation.mdx
  apps/frontend/app/[locale]/(main)/(vitnode)/error.tsx
  apps/frontend/app/[locale]/(main)/[...rest]/page.tsx
  apps/frontend/app/[locale]/(main)/not-found.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/not-found.tsx
  apps/frontend/app/[locale]/admin/(auth)/error.tsx
  apps/frontend/app/[locale]/global.css
  bump-version.mjs
  packages/create-vitnode-app/templates/basic/apps/frontend/app/[locale]/(main)/error.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/app/[locale]/(main)/not-found.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/app/[locale]/global.css
  packages/eslint-config-typescript-vitnode/.eslintrc.react.json
  packages/frontend/scripts/setup.ts
  packages/frontend/src/global.css
Labels: 🐞 Bug

#457 fix(backend): Update language session on Apollo Studio
  README.md
  __old_docs/pages/docs/deployment/_meta.json
  __old_docs/pages/docs/deployment/update.mdx
  __old_docs/pages/docs/themes/_meta.json
  __old_docs/pages/docs/themes/graphql.mdx
  __old_docs/pages/docs/themes/routing.mdx
  __old_docs/pages/docs/themes/virtualization.mdx
  apps/docs/app/(home)/page.tsx
  apps/docs/assets/dev/versioning.webp
  apps/docs/content/docs/dev/codegen.mdx
  apps/docs/content/docs/dev/deployment/index.mdx
  apps/docs/content/docs/dev/deployment/meta.json
  apps/docs/content/docs/dev/deployment/self-hosted.mdx
  apps/docs/content/docs/dev/deployment/update.mdx
  apps/docs/content/docs/dev/index.mdx
  apps/docs/content/docs/dev/meta.json
  apps/docs/content/docs/dev/pages-admin.mdx
  apps/docs/content/docs/dev/pages-permissions-admin.mdx
  apps/docs/content/docs/ui/navigation.mdx
  apps/docs/utils/modes.ts
  apps/frontend/app/[locale]/(main)/error.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/error.tsx
  packages/backend/src/core/sessions/authorization/internal/internal_authorization.service.ts
  packages/frontend/src/views/theme/views/settings/nav/drawer.tsx
  packages/frontend/src/views/theme/views/settings/nav/nav-settings.tsx
Labels: 🐞 Bug

#458 refactor(secure.mdx): SSH Configuration and Fix Typos
  __old_docs/pages/docs/deployment/secure.mdx
Labels: 🧱 Refactor

#460 fix(backend): Parser URL for cookie
  packages/backend/src/app.module.ts
Labels: 🐞 Bug

#461 feat(backend): Add support for http protocol
  packages/backend/src/app.module.ts
  packages/backend/src/core/admin/sessions/sign_out/sign_out.service.ts
  packages/backend/src/core/sessions/authorization/internal/internal_authorization.service.ts
  packages/backend/src/core/sessions/sign_in/device.service.ts
  packages/backend/src/core/sessions/sign_in/sign_in.service.ts
  packages/backend/src/core/sessions/sign_out/sign_out.service.ts
Labels: 💡 Feature

#462 fix(frontend): Env path from monorepo
  packages/frontend/next.config.ts
  pnpm-lock.yaml
Labels: 🐞 Bug

#463 feat(frontend): Add slug routing for frontend pre build view
  README.md
  apps/docs/content/docs/dev/deployment/update.mdx
  apps/docs/content/docs/dev/index.mdx
  apps/docs/content/docs/ui/theme.mdx
  apps/frontend/app/[locale]/(main)/(vitnode)/[...slug]/page.tsx
  apps/frontend/app/[locale]/(main)/(vitnode)/login/page.tsx
  apps/frontend/app/[locale]/(main)/(vitnode)/profile/[id]/page.tsx
  apps/frontend/app/[locale]/(main)/(vitnode)/register/page.tsx
  apps/frontend/app/[locale]/(main)/(vitnode)/settings/[...slug]/page.tsx
  apps/frontend/app/[locale]/(main)/(vitnode)/settings/devices/page.tsx
  apps/frontend/app/[locale]/(main)/(vitnode)/settings/files/page.tsx
  apps/frontend/app/[locale]/(main)/(vitnode)/settings/layout.tsx
  apps/frontend/app/[locale]/(main)/(vitnode)/settings/page.tsx
  apps/frontend/app/[locale]/(main)/[...rest]/page.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/[...slug]/error.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/[...slug]/not-found.tsx
  apps/frontend/app/[locale]/admin/(auth)/(vitnode)/[...slug]/page.tsx
  packages/frontend/src/views/admin/views/slug.tsx
  packages/frontend/src/views/slug.tsx
  packages/frontend/src/views/theme/layout/header/user-bar/auth.tsx
  packages/frontend/src/views/theme/layout/quick-menu/drawer/drawer.tsx
  packages/frontend/src/views/theme/views/auth/sign/in/form/form-sign-in.tsx
  packages/frontend/src/views/theme/views/auth/sign/in/sign-in-view.tsx
  packages/frontend/src/views/theme/views/auth/sign/up/form/form-sign-up.tsx
  packages/frontend/src/views/theme/views/auth/sign/up/sign-up-view.tsx
  packages/frontend/src/views/theme/views/profile/profile-view.tsx
  packages/frontend/src/views/theme/views/settings/layout.tsx
  packages/frontend/src/views/theme/views/settings/nav/hooks/use-settings-view.ts
  packages/frontend/src/views/theme/views/settings/slug.tsx
Labels: 💡 Feature

#464 feat(frontend): Add className to layout components, remove "Powered by VitNode" component
  packages/frontend/src/views/admin/views/install/layout.tsx
  packages/frontend/src/views/admin/views/sign-in/sign-in-admin-view.tsx
  packages/frontend/src/views/global/index.ts
  packages/frontend/src/views/global/internal-error/internal-error-view.tsx
  packages/frontend/src/views/global/powered-by.tsx
  packages/frontend/src/views/theme/layout/footer.tsx
  packages/frontend/src/views/theme/layout/header/header.tsx
  packages/frontend/src/views/theme/layout/header/logo.tsx
  packages/frontend/src/views/theme/layout/header/user-bar/auth.tsx
  packages/frontend/src/views/theme/layout/header/user-bar/user-bar.tsx
  packages/frontend/src/views/theme/layout/nav/nav.tsx
  packages/frontend/src/views/theme/layout/quick-menu/quick-menu.tsx
Labels: 💡 Feature

#465 feat: Add force login into settings in AdminCP
  apps/backend/schema.gql
  apps/docs/assets/ui/theme-after.png
  apps/docs/assets/ui/theme-before.png
  apps/docs/content/docs/ui/theme.mdx
  apps/frontend/plugins/admin/langs/en.json
  apps/frontend/plugins/core/langs/en.json
  packages/backend/src/core/admin/nav/show/show.service.ts
  packages/backend/src/core/admin/settings/authorization/authorization.module.ts
  packages/backend/src/core/admin/settings/authorization/edit/dto/edit.args.ts
  packages/backend/src/core/admin/settings/authorization/edit/edit.resolver.ts
  packages/backend/src/core/admin/settings/authorization/edit/edit.service.ts
  packages/backend/src/core/admin/settings/authorization/show/dto/show.obj.ts
  packages/backend/src/core/admin/settings/authorization/show/show.resolver.ts
  packages/backend/src/core/admin/settings/authorization/show/show.service.ts
  packages/backend/src/core/admin/settings/settings.module.ts
  packages/backend/src/core/middleware/show/dto/show.obj.ts
  packages/backend/src/core/middleware/show/show.service.ts
  packages/backend/src/providers/config.ts
  packages/frontend/src/graphql/mutations/admin/settings/authorization/admin__core_authorization_settings__edit.generated.ts
  packages/frontend/src/graphql/mutations/admin/settings/authorization/admin__core_authorization_settings__edit.gql
  packages/frontend/src/graphql/queries/admin/settings/authorization/admin__core_authorization_settings__show.generated.ts
  packages/frontend/src/graphql/queries/admin/settings/authorization/admin__core_authorization_settings__show.gql
  packages/frontend/src/graphql/queries/core_middleware__show.generated.ts
  packages/frontend/src/graphql/queries/core_middleware__show.gql
  packages/frontend/src/graphql/types.ts
  packages/frontend/src/middleware.ts
  packages/frontend/src/views/admin/views/core/settings/authorization/authorization-settings-core-admin-view.tsx
  packages/frontend/src/views/admin/views/core/settings/authorization/content.tsx
  packages/frontend/src/views/admin/views/core/settings/authorization/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/settings/authorization/hooks/use-authorization-settings-form-admin.ts
  packages/frontend/src/views/admin/views/slug.tsx
Labels: 💡 Feature

#467 refactor(frontend): Alert
  apps/docs/app/global.css
  apps/docs/assets/ui/components/alert.png
  apps/docs/content/docs/ui/alert.mdx
  apps/frontend/plugins/admin/langs/en.json
  apps/frontend/plugins/core/langs/en.json
  packages/create-vitnode-app/templates/basic/apps/frontend/app/[locale]/global.css
  packages/frontend/src/components/ui/alert.tsx
  packages/frontend/src/global.css
  packages/frontend/src/views/admin/global/rebuild-required.tsx
  packages/frontend/src/views/admin/layout/auth/aside/avatar.tsx
  packages/frontend/src/views/admin/layout/auth/aside/search/search.tsx
  packages/frontend/src/views/admin/views/core/dashboard/dashboard-core-admin-view.tsx
  packages/frontend/src/views/admin/views/core/styles/nav/table/actions/delete/content.tsx
  packages/frontend/src/views/admin/views/sign-in/form-sign-in-admin.tsx
  packages/frontend/src/views/theme/views/auth/sign/in/form/form-sign-in.tsx
Labels: 🧱 Refactor

#468 refactor: Rebuild envs
  .env.example
  apps/backend/package.json
  apps/docs/content/docs/dev/deployment/project.mdx
  apps/docs/content/docs/ui/forms/auto-form.mdx
  apps/frontend/Dockerfile
  apps/frontend/app/[locale]/(main)/page.tsx
  apps/frontend/package.json
  docker-compose.yml
  package.json
  packages/backend/package.json
  packages/backend/src/core/admin/email/helpers.service.ts
  packages/backend/src/core/admin/email/mail.service.ts
  packages/backend/src/utils/codegen.ts
  packages/create-vitnode-app/helpers/create-packages-json.ts
  packages/create-vitnode-app/package.json
  packages/create-vitnode-app/templates/basic/.env.template
  packages/create-vitnode-app/templates/create-vitnode.ts
  packages/frontend/codegen.ts
  packages/frontend/next.config.ts
  packages/frontend/package.json
  packages/frontend/src/components/ui/alert.tsx
  packages/frontend/src/components/ui/user/avatar.tsx
  packages/frontend/src/editor/extensions/files/client.tsx
  packages/frontend/src/editor/footer/files/item/item.tsx
  packages/frontend/src/editor/read-only/file-download-button.tsx
  packages/frontend/src/graphql/fetcher.ts
  packages/frontend/src/helpers/config-with-env.ts
  packages/frontend/src/views/admin/views/core/advanced/files/content.tsx
  packages/frontend/src/views/admin/views/core/settings/email/hooks/use-email-settings-form-admin.ts
  packages/frontend/src/views/admin/views/core/settings/metadata/manifest/hooks/use-manifest-core-admin-view.ts
  packages/frontend/src/views/admin/views/install/content/steps/welcome.tsx
  packages/frontend/src/views/admin/views/install/layout.tsx
  packages/frontend/src/views/theme/views/settings/views/files/content.tsx
  pnpm-lock.yaml
Labels: 🧱 Refactor

#469 perf(frontend): Remove confirm dialog when save changes in Theme Editor
  .env.example
  apps/docs/content/docs/dev/deployment/project.mdx
  apps/frontend/app/[locale]/layout.tsx
  apps/frontend/plugins/admin/langs/en.json
  apps/frontend/plugins/core/langs/en.json
  packages/backend/src/utils/database/client.ts
  packages/create-vitnode-app/templates/basic/.env.template
  packages/create-vitnode-app/templates/basic/apps/backend/src/database/config.ts
  packages/create-vitnode-app/templates/basic/apps/backend/src/main.ts
  packages/create-vitnode-app/templates/basic/apps/frontend/app/[locale]/layout.tsx
  packages/eslint-config-typescript-vitnode/eslint.shared.mjs
  packages/frontend/next.config.ts
  packages/frontend/package.json
  packages/frontend/src/components/ui/button.tsx
  packages/frontend/src/helpers/config-with-env.ts
  packages/frontend/src/views/admin/views/theme_editor/content.tsx
  packages/frontend/src/views/admin/views/theme_editor/hooks/use-theme-editor-api.ts
  packages/frontend/src/views/admin/views/theme_editor/hooks/use-theme-editor.ts
  packages/frontend/src/views/admin/views/theme_editor/sidebar/sidebar.tsx
  packages/frontend/src/views/admin/views/theme_editor/sidebar/submit.tsx
  packages/frontend/src/views/admin/views/theme_editor/sidebar/tabs/main.tsx
Labels: 🚀 Performerce

#470 perf(frontend)!: Add src dir
  apps/frontend/global.d.ts
  apps/frontend/src/app/[locale]/(main)/(vitnode)/[...slug]/page.tsx
  apps/frontend/src/app/[locale]/(main)/(vitnode)/settings/[...slug]/page.tsx
  apps/frontend/src/app/[locale]/(main)/(vitnode)/settings/layout.tsx
  apps/frontend/src/app/[locale]/(main)/(vitnode)/settings/page.tsx
  apps/frontend/src/app/[locale]/(main)/error.tsx
  apps/frontend/src/app/[locale]/(main)/layout.tsx
  apps/frontend/src/app/[locale]/(main)/not-found.tsx
  apps/frontend/src/app/[locale]/(main)/page.tsx
  apps/frontend/src/app/[locale]/admin/(auth)/(vitnode)/[...slug]/error.tsx
  apps/frontend/src/app/[locale]/admin/(auth)/(vitnode)/[...slug]/not-found.tsx
  apps/frontend/src/app/[locale]/admin/(auth)/(vitnode)/[...slug]/page.tsx
  apps/frontend/src/app/[locale]/admin/(auth)/(vitnode)/core/plugins/[code]/dev/files/page.tsx
  apps/frontend/src/app/[locale]/admin/(auth)/(vitnode)/core/plugins/[code]/dev/layout.tsx
  apps/frontend/src/app/[locale]/admin/(auth)/(vitnode)/core/plugins/[code]/dev/nav/page.tsx
  apps/frontend/src/app/[locale]/admin/(auth)/(vitnode)/core/plugins/[code]/dev/overview/page.tsx
  apps/frontend/src/app/[locale]/admin/(auth)/layout.tsx
  apps/frontend/src/app/[locale]/admin/(vitnode)/core/styles/theme-editor/page.tsx
  apps/frontend/src/app/[locale]/admin/(vitnode)/install/page.tsx
  apps/frontend/src/app/[locale]/admin/(vitnode)/page.tsx
  apps/frontend/src/app/[locale]/admin/layout.tsx
  apps/frontend/src/app/[locale]/error.tsx
  apps/frontend/src/app/[locale]/global.css
  apps/frontend/src/app/[locale]/layout.tsx
  apps/frontend/src/app/layout.tsx
  apps/frontend/src/app/not-found.tsx
  apps/frontend/src/i18n.ts
  apps/frontend/src/middleware.ts
  apps/frontend/src/plugins/admin/langs/en.json
  apps/frontend/src/plugins/core/langs/en.json
  apps/frontend/src/plugins/welcome/langs/en.json
  apps/frontend/src/plugins/welcome/templates/default-page.tsx
  apps/frontend/tailwind.config.ts
  bump-version.mjs
  packages/backend/scripts/generate-manifest.ts
  packages/backend/src/app.module.ts
  packages/backend/src/core/admin/theme_editor/edit/edit.service.ts
  packages/backend/src/core/theme_editor/show/show.service.ts
  packages/backend/src/providers/email/email.ts
  packages/create-vitnode-app/templates/basic/apps/frontend/src/app/[locale]/(main)/error.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/src/app/[locale]/(main)/layout.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/src/app/[locale]/(main)/not-found.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/src/app/[locale]/error.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/src/app/[locale]/global.css
  packages/create-vitnode-app/templates/basic/apps/frontend/src/app/[locale]/layout.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/src/app/layout.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/src/plugins/welcome/langs/en.json
  packages/create-vitnode-app/templates/basic/apps/frontend/src/plugins/welcome/langs/pl.json
  packages/create-vitnode-app/templates/basic/apps/frontend/src/plugins/welcome/templates/default-page.tsx
  packages/create-vitnode-app/templates/basic/apps/frontend/tailwind.config.ts
  packages/frontend/global.d.ts
  packages/frontend/scripts/setup.ts
Labels: 🚀 Performerce, 🚨 Breaking Changes

#471 fix(frontend): Copy files from package
  apps/backend/codegen.ts
  apps/frontend/tsconfig.json
  packages/create-vitnode-app/templates/basic/apps/backend/codegen.ts
  packages/create-vitnode-app/templates/basic/apps/frontend/tsconfig.json
  packages/frontend/scripts/setup.ts
Labels: 🐞 Bug

#473 fix(frontend): Error handle in fetcher
  apps/docs/content/docs/dev/captcha.mdx
  apps/docs/content/docs/dev/fetch.mdx
  apps/docs/content/docs/dev/files.mdx
  packages/frontend/src/editor/extensions/files/hooks/upload-mutation-api.ts
  packages/frontend/src/editor/footer/files/item/hooks/delete-mutation-api.ts
  packages/frontend/src/graphql/fetcher.ts
  packages/frontend/src/graphql/get-groups-short-api.ts
  packages/frontend/src/graphql/get-users-short-api.ts
  packages/frontend/src/hooks/core/sign/in/mutation-api.ts
  packages/frontend/src/hooks/core/sign/out/mutation-api.ts
  packages/frontend/src/hooks/core/sign/up/mutation-api.ts
  packages/frontend/src/views/admin/layout/auth/aside/hooks/mutation-api.ts
  packages/frontend/src/views/admin/layout/auth/aside/search/hooks/query-api.ts
  packages/frontend/src/views/admin/views/core/advanced/files/actions/delete/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/langs/create-edit/hooks/create-mutation-api.ts
  packages/frontend/src/views/admin/views/core/langs/create-edit/hooks/edit-mutation-api.ts
  packages/frontend/src/views/admin/views/core/langs/table/actions/delete/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/langs/table/actions/download/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/langs/table/actions/download/hooks/query-api.ts
  packages/frontend/src/views/admin/views/core/langs/table/actions/update/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/plugins/actions/create/hooks/mutation-create-api.ts
  packages/frontend/src/views/admin/views/core/plugins/actions/create/hooks/mutation-edit-api.ts
  packages/frontend/src/views/admin/views/core/plugins/views/dev/layout/actions/download/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/create-edit/hooks/create-mutation-api.ts
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/create-edit/hooks/edit-mutation-api.ts
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/item/actions/delete/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/plugins/views/dev/nav/item/hooks/mutation-change-position-api.ts
  packages/frontend/src/views/admin/views/core/settings/authorization/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/settings/email/actions/testing/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/settings/email/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/settings/main/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/settings/metadata/manifest/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/settings/security/captcha/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/styles/editor/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/styles/nav/create-edit/hooks/create-mutation-api.ts
  packages/frontend/src/views/admin/views/core/styles/nav/create-edit/hooks/edit-mutation-api.ts
  packages/frontend/src/views/admin/views/core/styles/nav/table/actions/delete/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/core/styles/nav/table/hooks/mutation-change-position-api.ts
  packages/frontend/src/views/admin/views/install/content/steps/database/mutation-api.ts
  packages/frontend/src/views/admin/views/members/groups/create-edit-form/hooks/mutation-create-api.ts
  packages/frontend/src/views/admin/views/members/groups/create-edit-form/hooks/mutation-edit-api.ts
  packages/frontend/src/views/admin/views/members/groups/table/actions/delete/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/members/staff/administrators/create-edit-form/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/members/staff/administrators/table/actions/delete/mutation-api.ts
  packages/frontend/src/views/admin/views/members/staff/moderators/create-edit-form/hooks/mutation-api.ts
  packages/frontend/src/views/admin/views/members/staff/moderators/table/actions/delete/mutation-api.ts
  packages/frontend/src/views/admin/views/theme_editor/hooks/mutation-api.ts
  packages/frontend/src/views/theme/views/settings/layout.tsx
  packages/frontend/src/views/theme/views/settings/views/overview/header/change-avatar/modal/cropper/hooks/mutation-api.ts
  packages/frontend/src/views/theme/views/settings/views/overview/header/change-avatar/modal/hooks/mutation-api.ts
Labels: 🐞 Bug
