Repository aXenDeveloper/vitnode, pull requests merged in 2024-03, with the labels that each got.

#239 feat(forum): Add stats to forum item
  backend/package.json
  backend/schema.gql
  backend/src/apps/admin/forum/forum.module.ts
  backend/src/apps/admin/forum/forums/create/create.service.ts
  backend/src/apps/admin/forum/forums/create/dto/create.obj.ts
  backend/src/apps/admin/forum/forums/edit/edit.service.ts
  backend/src/apps/admin/forum/forums/show/dto/show.args.ts
  backend/src/apps/admin/forum/forums/show/dto/show.obj.ts
  backend/src/apps/admin/forum/forums/show/show.resolver.ts
  backend/src/apps/admin/forum/forums/show/show.service.ts
  backend/src/apps/forum/forums/forums.module.ts
  backend/src/apps/forum/forums/show/dto/show.obj.ts
  backend/src/apps/forum/forums/show/show.service.ts
  backend/src/apps/forum/forums/show/stats.service.ts
  docs/package.json
  docs/pnpm-lock.yaml
  frontend/admin/forum/components/forums-select/list.tsx
  frontend/admin/forum/views/forums/table/hooks/use-forum-forums-admin-api.ts
  frontend/admin/forum/views/forums/table/item/actions/actions.tsx
  frontend/admin/forum/views/forums/table/item/actions/delete/delete.tsx
  frontend/admin/forum/views/forums/table/item/item.tsx
  frontend/components/icon/icon.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/mutations/forum/admin/forums/admin__forum_forums__show_short.gql
  frontend/graphql/queries/forum/admin/forums/admin__forum_forums__show.gql
  frontend/graphql/queries/forum/forum_forums__show.gql
  frontend/graphql/queries/forum/forum_forums__show_item.gql
  frontend/langs/en/forum.json
  frontend/langs/pl/forum.json
  frontend/next.config.js
  frontend/package.json
  frontend/themes/1/forum/views/forum/forums/category/category.tsx
  frontend/themes/1/forum/views/forum/forums/item/child.tsx
  frontend/themes/1/forum/views/forum/forums/item/item.tsx
  frontend/themes/1/forum/views/forum/forums/item/last-post.tsx
  frontend/themes/1/forum/views/forum/forums/item/stats.tsx
  frontend/themes/1/forum/views/forum/forums/item/wrapper-item-forum.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/forum-forum-view.tsx
  pnpm-lock.yaml
Labels: 💡 Feature

#242 fix(forum): Fix pointer-events on click on forum and topic item in forum view for mobile
  frontend/components/header-content/header-content.tsx
  frontend/themes/1/forum/views/forum/forums/item/item.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/topics-list/wrapper-item.tsx
Labels: 🐞 Bug

#243 fix(forum): Add max length for name topic to 100 characters
  backend/src/apps/admin/forum/database/schema/topics.ts
  backend/src/apps/forum/topics/create/dto/create.args.ts
  backend/src/types/database/text-language.type.ts
  frontend/hooks/forums/forum/topics/create/use-create-topic.ts
  frontend/langs/en/core.json
  frontend/langs/pl/core.json
Labels: 🐞 Bug

#244 fix(forum): Add max length for forum name
  backend/src/apps/admin/forum/database/schema/forums.ts
  docs/pages/frontend/components/editor.mdx
  docs/pages/frontend/i18n.mdx
  frontend/admin/core/views/members/groups/create-edit-form/hooks/use-create-edit-form-groups-members-admin.ts
  frontend/admin/forum/views/forums/create-edit/hooks/use-create-edit-form-forum-admin.ts
  frontend/functions/zod.ts
  frontend/hooks/forums/forum/posts/create/use-create-post.ts
  frontend/hooks/forums/forum/topics/create/use-create-topic.ts
  frontend/langs/en/core.json
  frontend/langs/pl/core.json
  frontend/themes/1/forum/views/forum/forums/item/item.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/topics-list/item.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/topics-list/wrapper-item.tsx
Labels: 🐞 Bug

#251 feat(frontend): Add before unload to form when isDirty is true
  frontend/admin/core/views/core/langs/create-edit/hooks/use-create-edit-lang-admin.tsx
  frontend/admin/core/views/core/langs/table/actions/download/hooks/use-download-lang-admin.ts
  frontend/admin/core/views/core/langs/table/actions/update/hooks/use-update-lang-admin.ts
  frontend/admin/core/views/core/plugins/actions/create/hooks/use-create-plugin-admin.ts
  frontend/admin/core/views/core/styles/nav/create-edit/hooks/use-create-edit-nav-admin.ts
  frontend/admin/core/views/core/styles/nav/table/actions/delete/content.tsx
  frontend/admin/core/views/core/styles/themes/actions/create/hooks/use-create-plugin-admin.ts
  frontend/admin/core/views/core/styles/themes/actions/upload/hooks/use-upload-theme.ts
  frontend/admin/core/views/core/styles/themes/table/actions/download/hooks/use-download-theme-admin.ts
  frontend/admin/core/views/core/styles/themes/table/actions/edit/hooks/use-edit-theme-admin.ts
  frontend/admin/core/views/members/groups/create-edit-form/hooks/use-create-edit-form-groups-members-admin.ts
  frontend/admin/core/views/members/staff/views/administrators/create-edit-form/hooks/use-form.ts
  frontend/admin/core/views/members/staff/views/moderators/create-edit-form/hooks/use-form.ts
  frontend/admin/forum/views/forums/create-edit/hooks/use-create-edit-form-forum-admin.ts
  frontend/admin/forum/views/forums/table/item/actions/delete/content.tsx
  frontend/components/ui/dialog.tsx
  frontend/components/ui/form.tsx
  frontend/hooks/core/settings/avatar/use-copper-modal-change-avatar.ts
  frontend/hooks/core/settings/avatar/use-modal-change-avatar.ts
  frontend/hooks/forums/forum/topics/create/use-create-topic.ts
  frontend/langs/en/core.json
  frontend/langs/pl/core.json
Labels: 💡 Feature

#252 perf(forum): Move create topic form form dialog to external page
  docs/pages/backend/_meta.json
  docs/pages/backend/practices.mdx
  docs/pages/frontend/_meta.json
  docs/pages/frontend/graphql.mdx
  docs/pages/frontend/pages.mdx
  docs/pages/frontend/practices.mdx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/create/page.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/layout.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/loading.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/page.tsx
  frontend/components/ui/card.tsx
  frontend/hooks/core/use-text-lang.ts
  frontend/langs/en/core.json
  frontend/langs/en/forum.json
  frontend/langs/pl/core.json
  frontend/langs/pl/forum.json
  frontend/themes/1/forum/views/forum/forums/actions/create-topic.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/actions/actions.tsx
  frontend/themes/1/forum/views/forum/forums/views/create-topic/create-topic-view.tsx
Labels: 🚀 Performerce

#255 fix(backend): Missing session id in know devices
  backend/src/apps/admin/core/database/schema/admins.ts
  backend/src/apps/admin/core/database/schema/sessions.ts
  backend/src/apps/core/middleware/middleware.cron.ts
  backend/src/apps/core/sessions/authorization/internal/internal_authorization.service.ts
  backend/src/apps/core/sessions/sign_in/device.service.ts
  backend/src/apps/core/sessions/sign_in/sign_in.service.ts
  backend/src/apps/forum/forums/show/show.service.ts
  docs/pages/contribution.mdx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/layout.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/query.ts
Labels: 🐞 Bug

#253 feat(frontend): Add breadcrumbs
  README.md
  backend/schema.gql
  backend/src/apps/admin/core/database/schema/admins.ts
  backend/src/apps/admin/core/database/schema/sessions.ts
  backend/src/apps/admin/forum/forums/create/create.service.ts
  backend/src/apps/admin/forum/forums/edit/edit.service.ts
  backend/src/apps/core/middleware/middleware.cron.ts
  backend/src/apps/core/sessions/authorization/internal/internal_authorization.service.ts
  backend/src/apps/core/sessions/sign_in/device.service.ts
  backend/src/apps/core/sessions/sign_in/sign_in.service.ts
  backend/src/apps/forum/forums/show/dto/show.obj.ts
  backend/src/apps/forum/forums/show/show.service.ts
  backend/src/apps/forum/forums/show/stats.service.ts
  backend/src/apps/forum/topics/create/create.service.ts
  backend/src/apps/forum/topics/show/dto/show.obj.ts
  backend/src/apps/forum/topics/show/show.service.ts
  backend/src/apps/forum/topics/topics.module.ts
  docs/pages/contribution.mdx
  docs/pages/frontend/pages.mdx
  frontend/admin/forum/views/forums/table/hooks/use-forum-forums-admin-api.ts
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/create/page.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/layout.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/loading.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/page.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/[id]/query.ts
  frontend/app/[locale]/(apps)/(main)/(container)/layout.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/topic/loading.tsx
  frontend/app/[locale]/(apps)/(main)/error.tsx
  frontend/app/[locale]/(apps)/(main)/not-found.tsx
  frontend/components/ui/breadcrumbs.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/queries/forum/forum_forums__show_item.gql
  frontend/graphql/queries/forum/topic/forum_topics__show.gql
  frontend/hooks/core/settings/use-settings-view.ts
  frontend/hooks/forums/forum/use-topics-list.ts
  frontend/langs/en/core.json
  frontend/langs/pl/core.json
  frontend/themes/1/core/layout/container-layout.tsx
  frontend/themes/1/core/layout/layout.tsx
  frontend/themes/1/core/views/settings/breadcrumbs.tsx
  frontend/themes/1/core/views/settings/layout-settings-view.tsx
  frontend/themes/1/forum/views/forum/forums/forums-forum-view.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/forum-forum-view.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/topics-list/topics-list.tsx
  frontend/themes/1/forum/views/forum/forums/views/create-topic/create-topic-view.tsx
  frontend/themes/1/forum/views/forum/topic/topic-view.tsx
Labels: 💡 Feature

#257 fix(forum): Omit display last post when user don't have permission to view topic
  backend/src/apps/admin/forum/forums/edit/edit.resolver.ts
  backend/src/apps/admin/forum/forums/edit/edit.service.ts
  backend/src/apps/forum/forums/show/show.service.ts
  backend/src/apps/forum/forums/show/stats.service.ts
  backend/src/apps/forum/topics/create/create.service.ts
  backend/src/apps/forum/topics/show/show.service.ts
  docs/pages/frontend/components/_meta.json
  docs/pages/frontend/components/breadcrumbs.mdx
  frontend/admin/core/views/sign-in/form/form-sign-in-admin.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/layout.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/topic/loading.tsx
  frontend/components/ui/breadcrumbs.tsx
  frontend/components/ui/form.tsx
  frontend/themes/1/core/views/auth/sign/in/form/form-sign-in.tsx
  frontend/themes/1/core/views/auth/sign/up/form/form-sign-up.tsx
  frontend/themes/1/core/views/global/error/error-view.tsx
  frontend/themes/1/forum/views/forum/forums/item/last-post/last-post.tsx
Labels: 🐞 Bug

#260 feat: Query for retrieving logged user's devices.
  backend/src/apps/core/sessions/devices/devices.module.ts
  backend/src/apps/core/sessions/devices/show/dto/show.args.ts
  backend/src/apps/core/sessions/devices/show/dto/show.obj.ts
  backend/src/apps/core/sessions/devices/show/show.resolver.ts
  backend/src/apps/core/sessions/devices/show/show.service.ts
  backend/src/apps/core/sessions/sessions.module.ts
Labels: 💡 Feature

#262 feat(plugins): Add upload plugin
  backend/modules/core/admin/database/schema/plugins.ts
  backend/modules/core/admin/plugins/download/download.service.ts
  backend/modules/core/admin/plugins/helpers/files/create/create-files.service.ts
  backend/modules/core/admin/plugins/plugins.module.ts
  backend/modules/core/admin/plugins/upload/dto/upload.args.ts
  backend/modules/core/admin/plugins/upload/upload.resolver.ts
  backend/modules/core/admin/plugins/upload/upload.service.ts
  backend/modules/core/admin/themes/upload/dto/upload.args.ts
  backend/modules/core/admin/themes/upload/upload.resolver.ts
  backend/modules/core/admin/themes/upload/upload.service.ts
  backend/modules/core/plugin.json
  backend/modules/forum/plugin.json
  backend/schema.gql
  frontend/admin/core/views/core/plugins/actions/upload/content.tsx
  frontend/admin/core/views/core/plugins/actions/upload/hooks/mutation-api.ts
  frontend/admin/core/views/core/plugins/actions/upload/hooks/use-upload-plugin-admin.ts
  frontend/admin/core/views/core/plugins/actions/upload/upload.tsx
  frontend/admin/core/views/core/styles/themes/actions/upload/content.tsx
  frontend/admin/core/views/core/styles/themes/actions/upload/hooks/use-upload-theme-admin.ts
  frontend/components/ui/sonner.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/mutations/admin/plugins/admin__core_plugins__upload.gql
  frontend/graphql/mutations/admin/themes/core_themes__admin__upload.gql
  frontend/langs/en/admin.json
  frontend/langs/pl/admin.json
Labels: 💡 Feature

#264 feat(plugins): Add files detected when create new version to count files
  backend/modules/blogs/admin/admin.module.ts
  backend/modules/blogs/admin/database/functions.ts
  backend/modules/blogs/admin/database/index.ts
  backend/modules/blogs/blogs.module.ts
  backend/modules/blogs/plugin.json
  backend/modules/blogs/versions.json
  backend/modules/database/schema.ts
  backend/modules/modules.module.ts
  frontend/admin/core/views/core/plugins/table/actions/download/check-list.tsx
  frontend/admin/core/views/core/plugins/table/actions/download/content.tsx
  frontend/admin/core/views/core/plugins/table/actions/download/hooks/query-api.ts
  frontend/admin/core/views/core/plugins/table/actions/download/hooks/use-download-plugin-admin.ts
  frontend/graphql/hooks.ts
  frontend/graphql/queries/admin/plugins/admin__core_plugins__download_check.gql
  frontend/langs/en/admin.json
  frontend/langs/pl/admin.json
Labels: 💡 Feature

#271 feat(plugins): Add change templates in frontend function in upload mutation
  backend/modules/blogs/admin/admin.module.ts
  backend/modules/blogs/admin/database/functions.ts
  backend/modules/blogs/admin/database/index.ts
  backend/modules/blogs/blogs.module.ts
  backend/modules/blogs/plugin.json
  backend/modules/blogs/versions.json
  backend/modules/core/admin/plugins/upload/upload.service.ts
  backend/modules/core/admin/themes/change_templates.service.ts
  backend/modules/core/admin/themes/upload/upload.service.ts
  backend/modules/database/schema.ts
  backend/modules/modules.module.ts
  docs/pages/themes/overview.mdx
  frontend/admin/core/views/core/plugins/create-edit/hooks/use-create-edit-plugin-admin.ts
  frontend/app/[locale]/(apps)/(admin)/admin/(auth)/core/plugins/[code]/dev/page.tsx
  frontend/langs/en/admin.json
  frontend/langs/pl/admin.json
Labels: 💡 Feature

#273 perf(backend)!: Change unix time to timestamp in database
  backend/configuration.ts
  backend/modules/core/admin/database/schema/admins.ts
  backend/modules/core/admin/database/schema/groups.ts
  backend/modules/core/admin/database/schema/languages.ts
  backend/modules/core/admin/database/schema/moderators.ts
  backend/modules/core/admin/database/schema/plugins.ts
  backend/modules/core/admin/database/schema/sessions.ts
  backend/modules/core/admin/database/schema/themes.ts
  backend/modules/core/admin/database/schema/users.ts
  backend/modules/core/admin/groups/create/create.service.ts
  backend/modules/core/admin/groups/edit/edit.service.ts
  backend/modules/core/admin/groups/show/dto/show.obj.ts
  backend/modules/core/admin/groups/show/show.service.ts
  backend/modules/core/admin/install/create_database/create_database.service.ts
  backend/modules/core/admin/languages/create/create.service.ts
  backend/modules/core/admin/members/members.module.ts
  backend/modules/core/admin/members/stats/stats.resolver.ts
  backend/modules/core/admin/members/stats/stats.service.ts
  backend/modules/core/admin/plugins/create/create.service.ts
  backend/modules/core/admin/plugins/show/dto/show.obj.ts
  backend/modules/core/admin/plugins/upload/upload.service.ts
  backend/modules/core/admin/staff/administrators/create/create.service.ts
  backend/modules/core/admin/staff/administrators/show/dto/show.obj.ts
  backend/modules/core/admin/staff/moderators/create/create.service.ts
  backend/modules/core/admin/staff/moderators/show/dto/show.obj.ts
  backend/modules/core/admin/themes/create/create.service.ts
  backend/modules/core/admin/themes/show/dto/show.obj.ts
  backend/modules/core/admin/themes/upload/upload.service.ts
  backend/modules/core/members/show/dto/show.obj.ts
  backend/modules/core/members/sign_up/sign_up.service.ts
  backend/modules/core/middleware/middleware.cron.ts
  backend/modules/core/sessions/authorization/internal/internal_authorization.service.ts
  backend/modules/core/sessions/devices/show/dto/show.obj.ts
  backend/modules/core/sessions/sessions.cron.ts
  backend/modules/core/sessions/sign_in/device.service.ts
  backend/modules/core/sessions/sign_in/sign_in.service.ts
  backend/modules/core/themes/change/change.service.ts
  backend/modules/forum/admin/database/schema/forums.ts
  backend/modules/forum/admin/database/schema/posts.ts
  backend/modules/forum/admin/database/schema/topics.ts
  backend/modules/forum/admin/forums/create/create.service.ts
  backend/modules/forum/forums/show/dto/show.obj.ts
  backend/modules/forum/forums/show/last_posts/dto/last_posts.obj.ts
  backend/modules/forum/posts/create/create.service.ts
  backend/modules/forum/posts/show/dto/show.obj.ts
  backend/modules/forum/topics/actions/lock_unlock/lock_toggle.service.ts
  backend/modules/forum/topics/create/create.service.ts
  backend/modules/forum/topics/show/dto/show.obj.ts
  backend/schema.gql
  frontend/codegen.ts
  frontend/components/date-format.tsx
  frontend/graphql/hooks.ts
  frontend/themes/1/forum/views/forum/topic/posts/post/post.tsx
Labels: 🚀 Performerce, 🚨 Breaking Changes

#274 feat(backend): Add time_24 and locale for core_languages table
  backend/modules/core/admin/database/schema/languages.ts
  backend/modules/core/admin/install/create_database/create_database.service.ts
  backend/modules/core/admin/languages/create/create.resolver.ts
  backend/modules/core/admin/languages/create/create.service.ts
  backend/modules/core/admin/languages/create/dto/create.args.ts
  backend/modules/core/admin/languages/edit/dto/edit.args.ts
  backend/modules/core/languages/show/dto/show.obj.ts
  backend/modules/core/languages/show/show.service.ts
  backend/schema.gql
  frontend/admin/core/views/core/dashboard/sign-up-stats.tsx
  frontend/admin/core/views/core/langs/create-edit/create-edit.tsx
  frontend/admin/core/views/core/langs/create-edit/hooks/use-create-edit-lang-admin.tsx
  frontend/components/date-format.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/mutations/admin/languages/admin__core_languages__create.gql
  frontend/graphql/mutations/admin/languages/admin__core_languages__edit.gql
  frontend/graphql/queries/core/core_middleware.gql
  frontend/graphql/queries/core/languages/core_languages__show.gql
  frontend/langs/en/admin.json
  frontend/langs/pl/admin.json
Labels: 💡 Feature

#275 feat(admin): Add version of VitNode
  backend/functions/config/get-config-file.ts
  backend/modules/core/admin/sessions/authorization/authorization.service.ts
  backend/modules/core/admin/sessions/authorization/dto/authorization.obj.ts
  backend/schema.gql
  frontend/admin/core/hooks/use-session-admin.ts
  frontend/admin/core/views/core/dashboard/dashboard-core-admin-view.tsx
  frontend/admin/core/views/core/dashboard/version.tsx
  frontend/admin/core/views/core/langs/table/actions/download/content.tsx
  frontend/app/[locale]/(apps)/(admin)/admin/(auth)/session-admin-provider.tsx
  frontend/components/ui/command.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/queries/admin/admin__sessions__authorization.gql
  frontend/graphql/queries/core/core_sessions__authorization.gql
Labels: 💡 Feature

#278 fix(frontend): Add useTransition for search in data-table
  frontend/components/data-table/data-table.tsx
  frontend/components/data-table/skeleton.tsx
  frontend/components/data-table/toolbar/search.tsx
  frontend/components/data-table/toolbar/toolbar.tsx
Labels: 🐞 Bug

#277 feat(plugins): Add search engine in AdminCP
  backend/modules/core/admin/plugins/show/dto/show.args.ts
  backend/modules/core/admin/plugins/show/show.service.ts
  backend/schema.gql
  frontend/admin/core/views/core/plugins/table/content.tsx
  frontend/app/[locale]/(apps)/(admin)/admin/(auth)/core/plugins/page.tsx
  frontend/components/data-table/data-table.tsx
  frontend/components/data-table/skeleton.tsx
  frontend/components/data-table/toolbar/search.tsx
  frontend/components/data-table/toolbar/toolbar.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/queries/admin/plugins/admin__core_plugins__show.gql
  frontend/langs/en/admin.json
  frontend/langs/pl/admin.json
Labels: 💡 Feature

#276 perf(plugins): Change created column to created in AdminCP
  backend/modules/core/admin/plugins/edit/edit.service.ts
  backend/modules/core/admin/plugins/show/dto/show.args.ts
  backend/modules/core/admin/plugins/show/dto/show.obj.ts
  backend/modules/core/admin/plugins/show/show.service.ts
  backend/modules/core/admin/plugins/upload/upload.service.ts
  backend/schema.gql
  frontend/admin/core/views/core/plugins/table/content.tsx
  frontend/app/[locale]/(apps)/(admin)/admin/(auth)/core/plugins/page.tsx
  frontend/components/data-table/data-table.tsx
  frontend/components/data-table/skeleton.tsx
  frontend/components/data-table/toolbar/search.tsx
  frontend/components/data-table/toolbar/toolbar.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/queries/admin/plugins/admin__core_plugins__show.gql
  frontend/langs/en/admin.json
  frontend/langs/pl/admin.json
Labels: 🚀 Performerce

#279 feat(langs): Add search engine in AdminCP
  backend/modules/core/languages/show/dto/show.args.ts
  backend/modules/core/languages/show/show.service.ts
  backend/schema.gql
  frontend/admin/core/views/core/langs/table/content.tsx
  frontend/app/[locale]/(apps)/(admin)/admin/(auth)/core/langs/page.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/queries/core/languages/core_languages__show.gql
  frontend/langs/en/admin.json
  frontend/langs/en/core.json
  frontend/langs/pl/admin.json
  frontend/langs/pl/core.json
Labels: 💡 Feature

#280 feat(langs): Add update column in AdminCP
  backend/modules/core/admin/languages/edit/edit.service.ts
  backend/modules/core/admin/languages/update/update.service.ts
  backend/modules/core/admin/plugins/show/dto/show.args.ts
  backend/modules/core/languages/show/dto/show.args.ts
  backend/modules/core/languages/show/dto/show.obj.ts
  backend/modules/core/languages/show/show.service.ts
  backend/schema.gql
  frontend/admin/core/views/core/langs/table/content.tsx
  frontend/admin/core/views/core/plugins/table/content.tsx
  frontend/app/[locale]/(apps)/(admin)/admin/(auth)/core/langs/page.tsx
  frontend/components/editor/toolbar/buttons/language-button.tsx
  frontend/components/switchers/language-switcher.tsx
  frontend/components/text-language-input.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/queries/core/languages/core_languages__show.gql
  frontend/hooks/core/use-globals.ts
Labels: 💡 Feature

#281 feat(lang): Add search engine for locale and timezone in create/edit lang form
  backend/modules/core/admin/languages/edit/edit.service.ts
  backend/modules/core/admin/plugins/edit/edit.service.ts
  frontend/admin/core/views/core/langs/create-edit/create-edit.tsx
  frontend/admin/core/views/core/langs/create-edit/fields/locale.tsx
  frontend/admin/core/views/core/langs/create-edit/fields/timezone.tsx
  frontend/admin/core/views/core/plugins/create-edit/hooks/use-create-edit-plugin-admin.ts
Labels: 💡 Feature

#282 feat: Add dynamic drag & drop
  frontend/admin/core/views/core/styles/nav/table/content.tsx
  frontend/admin/core/views/core/styles/nav/table/item.tsx
  frontend/admin/forum/views/forums/create-edit/hooks/mutation-create-api.ts
  frontend/admin/forum/views/forums/table/content-table.tsx
  frontend/admin/forum/views/forums/table/hooks/use-forum-forums-admin-api.ts
  frontend/admin/forum/views/forums/table/item/item.tsx
  frontend/hooks/core/drag&drop/use-functions.ts
  frontend/hooks/core/drag&drop/use-projection.ts
Labels: 💡 Feature

#284 feat(nav): Add icons
  backend/modules/blogs/admin/admin.module.ts
  backend/modules/blogs/admin/database/functions.ts
  backend/modules/blogs/admin/database/index.ts
  backend/modules/blogs/blogs.module.ts
  backend/modules/blogs/plugin.json
  backend/modules/blogs/versions.json
  backend/modules/core/admin/database/schema/nav.ts
  backend/modules/core/admin/nav/create/create.service.ts
  backend/modules/core/admin/nav/create/dto/create.args.ts
  backend/modules/core/admin/nav/edit/edit.service.ts
  backend/modules/core/nav/show/dto/show.obj.ts
  backend/modules/database/schema.ts
  backend/modules/modules.module.ts
  backend/schema.gql
  frontend/admin/core/views/core/plugins/table/item.tsx
  frontend/admin/core/views/core/styles/nav/create-edit/create-edit.tsx
  frontend/admin/core/views/core/styles/nav/create-edit/hooks/create-mutation-api.ts
  frontend/admin/core/views/core/styles/nav/create-edit/hooks/edit-mutation-api.ts
  frontend/admin/core/views/core/styles/nav/create-edit/hooks/use-create-edit-nav-admin.ts
  frontend/admin/core/views/core/styles/nav/table/actions/delete/delete.tsx
  frontend/admin/core/views/core/styles/nav/table/actions/edit.tsx
  frontend/admin/core/views/core/styles/nav/table/content.tsx
  frontend/admin/core/views/core/styles/nav/table/hooks/mutation-change-position-api.ts
  frontend/admin/core/views/core/styles/nav/table/item.tsx
  frontend/admin/forum/views/forums/table/item/item.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/mutations/admin/nav/core_nav__admin__create.gql
  frontend/graphql/mutations/admin/nav/core_nav__admin__edit.gql
  frontend/graphql/queries/admin/nav/admin__core_nav__show.gql
  frontend/graphql/queries/core/core_sessions__authorization.gql
  frontend/langs/en/admin.json
  frontend/langs/en/core.json
  frontend/langs/pl/admin.json
  frontend/langs/pl/core.json
  frontend/themes/1/core/layout/nav/item.tsx
Labels: 💡 Feature

#288 feat(redis)!: Remove redis
  .env.example
  README.md
  backend/.env.example
  backend/main.ts
  backend/package.json
  backend/redis.adapter.ts
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-test.yml
  docs/pages/dev.mdx
  docs/pages/requirements.mdx
  docs/pages/setup/install.mdx
  pnpm-lock.yaml
Labels: 💡 Feature, 🚨 Breaking Changes

#287 feat(admin): Add dynamic navigation from plugins
  .env.example
  README.md
  backend/.env.example
  backend/functions/config/finish-build-config-file.ts
  backend/functions/config/update-plugins.ts
  backend/main.ts
  backend/modules/core/admin/database/migrations/0000_material_wolverine.sql
  backend/modules/core/admin/database/migrations/meta/0000_snapshot.json
  backend/modules/core/admin/database/migrations/meta/_journal.json
  backend/modules/core/admin/database/schema/plugins.ts
  backend/modules/core/admin/install/create_database/create_database.service.ts
  backend/modules/core/admin/plugins/create/create.service.ts
  backend/modules/core/admin/plugins/download/download.service.ts
  backend/modules/core/admin/plugins/helpers/files/create/contents.ts
  backend/modules/core/admin/plugins/plugins.module.ts
  backend/modules/core/admin/plugins/upload/upload.service.ts
  backend/modules/core/admin/sessions/authorization/authorization.service.ts
  backend/modules/core/admin/sessions/authorization/dto/authorization.obj.ts
  backend/modules/core/admin/themes/change_templates.service.ts
  backend/modules/core/admin/themes/upload/upload.service.ts
  backend/modules/core/plugin.json
  backend/modules/forum/admin/database/migrations/0000_nostalgic_northstar.sql
  backend/modules/forum/admin/database/migrations/meta/0000_snapshot.json
  backend/modules/forum/admin/database/migrations/meta/_journal.json
  backend/modules/forum/plugin.json
  backend/package.json
  backend/redis.adapter.ts
  backend/schema.gql
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-test.yml
  docs/assets/dev/register_postgres.png
  docs/components/img.tsx
  docs/package.json
  docs/pages/dev.mdx
  docs/pages/requirements.mdx
  docs/pages/setup/install.mdx
  docs/pnpm-lock.yaml
  docs/tailwind.config.js
  frontend/admin/core/hooks/use-session-admin.ts
  frontend/admin/core/layout/nav/list/item/item.tsx
  frontend/admin/core/layout/nav/list/item/link.tsx
  frontend/admin/core/layout/nav/list/list-nav-admin.tsx
  frontend/admin/core/views/core/langs/table/content.tsx
  frontend/admin/core/views/core/plugins/table/actions/actions.tsx
  frontend/admin/core/views/core/plugins/views/dev/nav/table/item.tsx
  frontend/app/[locale]/(apps)/(admin)/admin/(auth)/session-admin-provider.tsx
  frontend/app/[locale]/(apps)/(main)/page.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/queries/admin/admin__sessions__authorization.gql
  frontend/langs/en/admin.json
  frontend/langs/en/core.json
  frontend/langs/en/forum.json
  frontend/langs/pl/admin.json
  frontend/langs/pl/core.json
  frontend/langs/pl/forum.json
  frontend/package.json
  frontend/themes/1/forum/default-page.tsx
  package.json
  pnpm-lock.yaml
Labels: 💡 Feature

#292 feat(blog): Create tables in database
  backend/functions/config/update-plugins.ts
  backend/plugins/blog/admin/database/index.ts
  backend/plugins/blog/admin/database/migrations/0000_crazy_siren.sql
  backend/plugins/blog/admin/database/migrations/0001_slow_diamondback.sql
  backend/plugins/blog/admin/database/migrations/meta/0000_snapshot.json
  backend/plugins/blog/admin/database/migrations/meta/0001_snapshot.json
  backend/plugins/blog/admin/database/migrations/meta/_journal.json
  backend/plugins/blog/admin/database/schema/articles.ts
  backend/plugins/blog/admin/database/schema/categories.ts
  backend/plugins/blog/plugin.json
  backend/plugins/blog/versions.json
  backend/plugins/core/admin/plugins/download/download.service.ts
  backend/plugins/core/admin/plugins/paths.ts
  backend/utils/guards/dev.guard.ts
  docs/pages/plugins/database/overview.mdx
Labels: 💡 Feature

#294 feat(blog): Add simple mutations and query for display categories in AdminCP
  backend/plugins/blog/admin/database/migrations/0001_naive_black_queen.sql
  backend/plugins/blog/admin/database/migrations/meta/0001_snapshot.json
  backend/plugins/blog/admin/database/migrations/meta/_journal.json
  backend/plugins/blog/admin/database/schema/categories.ts
  backend/plugins/blog/blog.module.ts
  backend/plugins/blog/categories/categories.module.ts
  backend/plugins/blog/categories/show/dto/show.args.ts
  backend/plugins/blog/categories/show/dto/show.obj.ts
  backend/plugins/blog/categories/show/show.resolver.ts
  backend/plugins/blog/categories/show/show.service.ts
  backend/plugins/core/admin/groups/show/dto/show.obj.ts
  backend/plugins/core/admin/plugins/delete/contents.ts
  backend/plugins/core/admin/plugins/delete/delete.service.ts
  backend/plugins/core/admin/plugins/helpers/files/change/contents.ts
  backend/plugins/core/admin/plugins/paths.ts
  backend/plugins/core/admin/plugins/upload/upload.service.ts
  backend/plugins/core/admin/sessions/authorization/authorization.service.ts
  backend/plugins/core/files/download/download.controller.ts
  backend/plugins/core/files/files.module.ts
  backend/plugins/database/schema.ts
  backend/plugins/plugins.module.ts
  backend/schema.gql
  docs/pages/frontend/_meta.json
  docs/pages/frontend/dark-light-mode.mdx
  docs/pages/plugins/_meta.json
  docs/pages/plugins/admin-pages.mdx
  docs/pages/plugins/authorization.mdx
  docs/pages/plugins/database/overview.mdx
  docs/pages/plugins/database/pagination.mdx
  docs/pages/plugins/database/sorting.mdx
  docs/pages/plugins/graphql.mdx
  docs/pages/plugins/i18n.mdx
  docs/pages/themes/_meta.json
  docs/pages/themes/fetch.mdx
  docs/pages/themes/forms.mdx
  docs/pages/themes/graphql.mdx
  frontend/admin/core/api-tags.ts
  frontend/admin/core/views/core/plugins/upload/hooks/mutation-api.ts
  frontend/app/[locale]/layout.tsx
  frontend/functions/get-session-data.ts
  frontend/hooks/core/middleware-query-api.ts
  frontend/i18n.ts
Labels: 💡 Feature

#295 perf(frontend)!: Refactor colors
  backend/package.json
  docs/assets/dev/register_postgres.png
  docs/assets/plugins/create_nav_admin.png
  docs/assets/plugins/create_nav_admin_form.png
  docs/assets/plugins/create_plugin.png
  docs/assets/plugins/finish_create_nav_admin.png
  docs/assets/plugins/open_devtools.png
  docs/assets/plugins/result_page_admin.png
  docs/assets/plugins/result_template_page_admin.png
  docs/pages/plugins/admin-pages.mdx
  frontend/admin/blog/views/categories/categories-view.tsx
  frontend/admin/core/global/rebuild-required.tsx
  frontend/admin/core/layout/admin-layout.tsx
  frontend/admin/core/layout/header/header-admin.tsx
  frontend/admin/core/layout/header/user-bar/user-bar-admin.tsx
  frontend/admin/core/layout/nav/list/item/item.tsx
  frontend/admin/core/layout/nav/nav-admin.tsx
  frontend/admin/core/views/core/langs/langs-core-admin-view.tsx
  frontend/admin/core/views/core/plugins/plugins-admin-view.tsx
  frontend/admin/core/views/core/plugins/views/dev/layout/layout.tsx
  frontend/admin/core/views/core/plugins/views/dev/nav/nav.tsx
  frontend/admin/core/views/core/settings/settings-core-admin-view.tsx
  frontend/admin/core/views/core/styles/nav/nav-admin-view.tsx
  frontend/admin/core/views/core/styles/themes/actions/upload.tsx
  frontend/admin/core/views/core/styles/themes/themes-admin-view.tsx
  frontend/admin/core/views/members/groups/groups-members-admin-view.tsx
  frontend/admin/core/views/members/staff/views/administrators/administrators-view.tsx
  frontend/admin/core/views/members/staff/views/moderators/moderators-view.tsx
  frontend/admin/core/views/members/users/users-members-admin-view.tsx
  frontend/admin/forum/views/forums/forums-forum-admin-view.tsx
  frontend/app/[locale]/(apps)/(admin)/admin/global.scss
  frontend/app/[locale]/(apps)/(main)/(container)/mod/page.tsx
  frontend/components/header-content/header-content.tsx
  frontend/components/logo-vitnode.tsx
  frontend/components/tabs/tabs.tsx
  frontend/langs/en/forum.json
  frontend/langs/pl/forum.json
  frontend/package.json
  frontend/themes/1/core/layout/global.scss
  frontend/themes/1/core/layout/header/user-bar/auth/auth-user-bar.tsx
  frontend/themes/1/core/layout/quick-menu/drawer/drawer.tsx
  frontend/themes/1/core/views/settings/layout-settings-view.tsx
  frontend/themes/1/forum/default-page.tsx
  frontend/themes/1/forum/views/forum/forums/category/chevron-button.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/forum-forum-view.tsx
  pnpm-lock.yaml
Labels: 🚀 Performerce, 🚨 Breaking Changes

#297 feat(blog): Add create form for category in AdminCP
  backend/plugins/blog/admin/admin.module.ts
  backend/plugins/blog/admin/categories/create/create.resolver.ts
  backend/plugins/blog/admin/categories/create/create.service.ts
  backend/plugins/blog/admin/categories/create/dto/create.args.ts
  backend/plugins/blog/admin/database/migrations/0000_odd_zarek.sql
  backend/plugins/blog/admin/database/migrations/meta/0000_snapshot.json
  backend/plugins/blog/admin/database/migrations/meta/0001_snapshot.json
  backend/plugins/blog/admin/database/schema/categories.ts
  backend/plugins/blog/categories/show/dto/show.obj.ts
  backend/plugins/blog/categories/show/show.service.ts
  backend/schema.gql
  docs/pages/setup/_meta.json
  docs/pages/setup/update.mdx
  docs/pages/themes/forms.mdx
  frontend/admin/blog/views/categories/actions/create.tsx
  frontend/admin/blog/views/categories/categories-view.tsx
  frontend/admin/blog/views/categories/create-edit/create-edit.tsx
  frontend/admin/blog/views/categories/create-edit/hooks/create-mutation-api.ts
  frontend/admin/blog/views/categories/create-edit/hooks/use-create-edit-category-blog-admin.ts
  frontend/admin/core/layout/admin-layout.tsx
  frontend/app/[locale]/(apps)/(admin)/admin/global.scss
  frontend/components/data-table/header.tsx
  frontend/components/ui/checkbox.tsx
  frontend/components/ui/dropdown-menu.tsx
  frontend/components/ui/radio-group.tsx
  frontend/components/ui/select.tsx
  frontend/components/ui/skeleton.tsx
  frontend/components/ui/table.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/mutations/blog/admin/categories/admin__blog_categories__create.gql
  frontend/langs/en/blog.json
  frontend/langs/pl/blog.json
  frontend/themes/1/blog/default-page.tsx
  frontend/themes/1/core/layout/global.scss
Labels: 💡 Feature
