Repository aXenDeveloper/vitnode, pull requests merged in 2024-04, with the labels that each got.

#300 refactor(frontend): Move nav to the left side
  backend/package.json
  backend/plugins/core/admin/database/schema/nav.ts
  backend/plugins/core/admin/nav/change_position/change_position.service.ts
  backend/plugins/core/admin/nav/change_position/dto/change_position.args.ts
  backend/plugins/core/admin/nav/create/create.service.ts
  backend/plugins/core/admin/nav/delete/delete.service.ts
  backend/plugins/core/nav/show/show.service.ts
  backend/plugins/forum/admin/database/schema/forums.ts
  backend/plugins/forum/admin/forums/change_position/dto/change_position.args.ts
  backend/plugins/forum/admin/forums/create/create.service.ts
  backend/plugins/forum/forums/show/show.service.ts
  backend/schema.gql
  docs/package.json
  docs/pages/_meta.json
  docs/pages/frontend/_meta.json
  docs/pages/frontend/notifications/_meta.json
  docs/pages/frontend/notifications/push.mdx
  docs/pages/frontend/notifications/toast.mdx
  docs/pages/themes/_meta.json
  docs/pages/themes/i18n.mdx
  docs/pages/themes/virtualization.mdx
  docs/pnpm-lock.yaml
  frontend/admin/core/views/core/styles/nav/create-edit/hooks/use-create-edit-nav-admin.ts
  frontend/app/[locale]/(apps)/(admin)/admin/global.scss
  frontend/components/logo-vitnode.tsx
  frontend/components/switchers/dark-light-mode-switcher.tsx
  frontend/components/switchers/language-switcher.tsx
  frontend/components/switchers/theme/theme-switcher.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/mutations/admin/nav/core_nav__admin__change_position.gql
  frontend/graphql/mutations/forum/admin/forums/admin__forum_forums__change_position.gql
  frontend/package.json
  frontend/tailwind.config.js
  frontend/tailwind.config.ts
  frontend/themes/1/core/layout/global.scss
  frontend/themes/1/core/layout/header/header.tsx
  frontend/themes/1/core/layout/header/user-bar/auth/auth-user-bar.tsx
  frontend/themes/1/core/layout/layout.tsx
  frontend/themes/1/core/layout/nav/item.tsx
  frontend/themes/1/core/layout/nav/nav.tsx
  frontend/themes/1/forum/views/forum/topic/posts/list.tsx
  frontend/themes/1/forum/views/forum/topic/posts/post/actions/actions.tsx
  frontend/themes/1/forum/views/forum/topic/posts/post/actions/delete/content.tsx
  frontend/tsconfig.json
  pnpm-lock.yaml
Labels: 🚀 Performerce

#305 refactor(forum)!: Remove forum_posts_timeline table
  backend/plugins/core/admin/database/schema/users.ts
  backend/plugins/forum/admin/database/schema/posts.ts
  backend/plugins/forum/admin/database/schema/topics.ts
  backend/plugins/forum/posts/create/create.service.ts
  backend/plugins/forum/posts/delete/delete.service.ts
  backend/plugins/forum/posts/show/dto/show.args.ts
  backend/plugins/forum/posts/show/dto/show.obj.ts
  backend/plugins/forum/posts/show/show.service.ts
  backend/plugins/forum/posts/topics.module.ts
  backend/plugins/forum/topics/actions/lock_unlock/lock_toggle.service.ts
  backend/plugins/forum/topics/create/create.service.ts
  backend/schema.gql
  frontend/app/[locale]/(apps)/(main)/(container)/forum/topic/[id]/page.tsx
  frontend/app/[locale]/(apps)/(main)/(container)/forum/topic/[id]/query-api.ts
  frontend/graphql/hooks.ts
  frontend/graphql/mutations/forum/post/forum_posts__create.gql
  frontend/graphql/queries/forum/topic/forum_posts__show_more.gql
  frontend/graphql/queries/forum/topic/forum_topics__show.gql
  frontend/hooks/forum/posts/use-more-posts.ts
  frontend/themes/1/forum/views/forum/topic/posts/list.tsx
  frontend/themes/1/forum/views/forum/topic/posts/load-more/load-more-posts.tsx
  frontend/themes/1/forum/views/forum/topic/posts/wrapper/use-wrapper-posts.ts
  frontend/themes/1/forum/views/forum/topic/posts/wrapper/wrapper.tsx
  frontend/themes/1/forum/views/forum/topic/topic-view.tsx
Labels: 🚀 Performerce, 🚨 Breaking Changes

#310 feat(admin): Add useOptimistic for switch language
  backend/package.json
  backend/plugins/blog/admin/database/migrations/0000_magical_blackheart.sql
  backend/plugins/blog/admin/database/migrations/meta/0000_snapshot.json
  backend/plugins/blog/admin/database/migrations/meta/_journal.json
  backend/plugins/core/admin/database/migrations/0000_last_mojo.sql
  backend/plugins/core/admin/database/migrations/meta/0000_snapshot.json
  backend/plugins/core/admin/database/migrations/meta/_journal.json
  backend/plugins/core/admin/languages/download/download.service.ts
  backend/plugins/core/admin/languages/update/update.service.ts
  backend/plugins/core/admin/plugins/delete/delete.service.ts
  backend/plugins/core/admin/plugins/upload/upload.service.ts
  backend/plugins/core/admin/themes/download/download.service.ts
  backend/plugins/core/admin/themes/upload/upload.service.ts
  backend/plugins/forum/admin/database/migrations/0000_sudden_umar.sql
  backend/plugins/forum/admin/database/migrations/meta/0000_snapshot.json
  backend/plugins/forum/admin/database/migrations/meta/_journal.json
  frontend/admin/core/views/core/langs/table/enabled-row.tsx
  frontend/admin/core/views/core/langs/table/table.tsx
  frontend/app/[locale]/layout.tsx
  frontend/i18n.ts
  frontend/langs/en/core.json
  frontend/langs/pl/core.json
  frontend/package.json
  pnpm-lock.yaml
Labels: 💡 Feature

#312 feat: Add update config.json when run project
  backend/functions/config/generate-config-file.ts
  frontend/themes/1/core/layout/layout.tsx
Labels: 💡 Feature

#313 feat(sitemap): Add automatic generate sitemap
  .env.example
  backend/config/configuration.ts
  backend/main.ts
  backend/plugins/core/plugins/show/dto/show.obj.ts
  backend/plugins/core/plugins/show/show.service.ts
  backend/schema.gql
  docker-compose-prod-backend.yml
  docs/package.json
  docs/pages/dev.mdx
  docs/pages/plugins/_meta.json
  docs/pages/plugins/sitemap.mdx
  docs/pages/setup/install.mdx
  docs/pnpm-lock.yaml
  frontend/app/[locale]/(admin)/admin/(auth)/core/settings/layout.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/core/settings/sitemap/page.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/loading.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/not-found.tsx
  frontend/app/[locale]/(admin)/admin/global.scss
  frontend/app/[locale]/(admin)/admin/loading.tsx
  frontend/app/[locale]/(admin)/admin/not-found.tsx
  frontend/app/[locale]/(main)/(container)/forum/sitemap.ts
  frontend/app/[locale]/(main)/forum/page.tsx
  frontend/app/[locale]/(main)/loading.tsx
  frontend/app/[locale]/layout.tsx
  frontend/app/robots.ts
  frontend/app/sitemap.ts
  frontend/components/ui/button.tsx
  frontend/config.ts
  frontend/functions/sitemap.ts
  frontend/graphql/hooks.ts
  frontend/graphql/queries/core/core_sessions__authorization.gql
  frontend/graphql/queries/forum/forum_forums__show__sitemap.gql
  frontend/hooks/core/use-text-lang.ts
  frontend/langs/en/admin.json
  frontend/langs/pl/admin.json
  frontend/middleware.ts
  frontend/themes/1/core/layout/global.scss
Labels: 💡 Feature

#315 fix(themes): Custom light doesn't change after change layout
  backend/plugins/core/admin/plugins/create/create.service.ts
  backend/plugins/core/admin/sessions/authorization/authorization.service.ts
  backend/plugins/core/admin/sessions/authorization/dto/authorization.obj.ts
  backend/plugins/core/admin/themes/create/create.service.ts
  backend/plugins/core/admin/themes/delete/delete.service.ts
  backend/plugins/core/admin/themes/upload/upload.service.ts
  backend/plugins/core/sessions/authorization/authorization.service.ts
  backend/plugins/core/sessions/authorization/dto/authorization.obj.ts
  backend/schema.gql
  frontend/admin/core/global/internal-error/internal-error-view.tsx
  frontend/admin/core/global/rebuild-required.tsx
  frontend/admin/core/hooks/use-session-admin.ts
  frontend/admin/core/layout/header/header-admin.tsx
  frontend/admin/core/layout/header/lang-switcher.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/session-admin-provider.tsx
  frontend/app/[locale]/(main)/session-provider.tsx
  frontend/app/[locale]/catch.tsx
  frontend/app/[locale]/layout.tsx
  frontend/components/switchers/language-switcher.tsx
  frontend/components/switchers/theme/theme-switcher.tsx
  frontend/components/ui/form.tsx
  frontend/functions/colors.ts
  frontend/graphql/hooks.ts
  frontend/graphql/queries/admin/admin__sessions__authorization.gql
  frontend/graphql/queries/core/core_sessions__authorization.gql
  frontend/hooks/core/use-session.ts
  frontend/themes/1/core/layout/global.scss
Labels: 🐞 Bug

#316 perf!: Move static files form backend to frontend
  backend/app.module.ts
  backend/functions/config/manifest.ts
  backend/package.json
  backend/plugins/core/admin/metadata/manifest/edit/edit.service.ts
  backend/plugins/core/admin/metadata/manifest/functions.ts
  backend/plugins/core/admin/settings/main/edit/edit.service.ts
  backend/plugins/core/files/delete/delete.service.ts
  backend/plugins/core/files/upload/upload.service.ts
  backend/plugins/core/settings/show/show.service.ts
  backend/public/index.html
  docker-compose-prod-backend.yml
  docker-compose-prod-frontend.yml
  frontend/.gitignore
  frontend/app/[locale]/layout.tsx
  frontend/app/layout.tsx
  frontend/components/switchers/theme/theme-switcher.tsx
  frontend/components/user/avatar/avatar-user.tsx
  frontend/middleware.ts
  frontend/next.config.js
  frontend/public/icons/favicon.ico
  pnpm-lock.yaml
Labels: 🚀 Performerce, 🚨 Breaking Changes

#317 feat(editor): Add insert image
  backend/package.json
  docs/package.json
  docs/pages/themes/components/editor.mdx
  docs/pnpm-lock.yaml
  frontend/admin/core/views/core/styles/editor/content.tsx
  frontend/components/editor/editor.tsx
  frontend/components/editor/extensions/extensions.ts
  frontend/components/editor/extensions/heading.tsx
  frontend/components/editor/extensions/image/client.tsx
  frontend/components/editor/extensions/image/image.tsx
  frontend/components/editor/extensions/image/server.tsx
  frontend/components/editor/read-only.tsx
  frontend/components/editor/read-only/read-only.tsx
  frontend/components/img.tsx
  frontend/next.config.js
  frontend/package.json
  frontend/themes/1/core/layout/header/header.tsx
  frontend/themes/1/forum/views/forum/forums/category/category.tsx
  frontend/themes/1/forum/views/forum/forums/item/item.tsx
  frontend/themes/1/forum/views/forum/forums/views/[id]/forum-forum-view.tsx
  frontend/themes/1/forum/views/forum/topic/posts/post/post.tsx
  package.json
  pnpm-lock.yaml
  prettier.config.mjs
Labels: 💡 Feature

#318 feat(editor): Add highlight for code block in read-only parser
  .vscode/settings.json
  frontend/app/[locale]/(admin)/admin/(auth)/core/loading.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/core/plugins/[code]/dev/loading.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/members/groups/loading.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/members/loading.tsx
  frontend/app/[locale]/(admin)/admin/(auth)/members/staff/loading.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/install/loading.tsx
  frontend/app/[locale]/(admin)/admin/(configs)/loading.tsx
  frontend/app/[locale]/(admin)/admin/global.scss
  frontend/app/[locale]/(main)/(container)/forum/[id]/loading.tsx
  frontend/app/[locale]/(main)/(container)/forum/topic/loading.tsx
  frontend/components/editor/extensions/code/client.ts
  frontend/components/editor/extensions/code/code-block-component.tsx
  frontend/components/editor/extensions/code/code.tsx
  frontend/components/editor/extensions/extensions.ts
  frontend/components/editor/extensions/image/client.ts
  frontend/components/editor/read-only/code-block.tsx
  frontend/components/editor/read-only/read-only.tsx
  frontend/components/editor/toolbar/toolbar.tsx
  frontend/functions/generate-random-string.ts
  frontend/langs/en/core.json
  frontend/langs/pl/core.json
  frontend/themes/1/core/layout/global.scss
  frontend/themes/1/core/layout/quick-menu/quick-menu.tsx
Labels: 💡 Feature

#319 feat(editor): Add emojis
  docs/pages/themes/components/editor.mdx
  frontend/components/editor/editor.tsx
  frontend/components/editor/extensions/code/code.tsx
  frontend/components/editor/extensions/emoji/client.tsx
  frontend/components/editor/extensions/emoji/emoji.tsx
  frontend/components/editor/extensions/extensions.ts
  frontend/components/editor/extensions/image/image.ts
  frontend/components/editor/extensions/mentions/client.tsx
  frontend/components/editor/extensions/mentions/emoji.tsx
  frontend/components/editor/toolbar/custom/emoji/content.tsx
  frontend/components/editor/toolbar/custom/emoji/emoji.tsx
  frontend/components/editor/toolbar/toolbar.tsx
  frontend/components/icon/input/content/content.tsx
  frontend/components/icon/input/content/emojis/emojis.tsx
  frontend/components/icon/input/content/emojis/skin-select.tsx
  frontend/components/icon/input/icon-input.tsx
  frontend/components/ui/popover.tsx
  frontend/components/ui/skeleton.tsx
  frontend/langs/en/core.json
  frontend/langs/pl/core.json
  frontend/package.json
  frontend/tailwind.config.ts
  frontend/themes/1/forum/views/forum/topic/posts/create/create-post.tsx
  frontend/themes/1/forum/views/forum/topic/topic-view.tsx
  pnpm-lock.yaml
Labels: 💡 Feature

#321 refactor(backend)!: Change sortBy from array to object
  backend/functions/database/pagination.ts
  backend/plugins/blog/categories/show/show.service.ts
  backend/plugins/core/admin/groups/show/dto/show.args.ts
  backend/plugins/core/admin/groups/show/show.service.ts
  backend/plugins/core/admin/members/show/dto/show.args.ts
  backend/plugins/core/admin/members/show/show.service.ts
  backend/plugins/core/admin/plugins/show/dto/show.args.ts
  backend/plugins/core/admin/plugins/show/show.service.ts
  backend/plugins/core/admin/staff/administrators/show/dto/show.args.ts
  backend/plugins/core/admin/staff/administrators/show/show.service.ts
  backend/plugins/core/admin/staff/moderators/show/dto/show.args.ts
  backend/plugins/core/admin/staff/moderators/show/show.service.ts
  backend/plugins/core/admin/themes/show/dto/show.args.ts
  backend/plugins/core/admin/themes/show/show.service.ts
  backend/plugins/core/files/show/dto/show.args.ts
  backend/plugins/core/files/show/show.service.ts
  backend/plugins/core/languages/show/dto/show.args.ts
  backend/plugins/core/languages/show/show.service.ts
  backend/plugins/core/members/show/dto/show.args.ts
  backend/plugins/core/members/show/show.service.ts
  backend/plugins/core/nav/show/show.service.ts
  backend/plugins/core/sessions/devices/show/show.service.ts
  backend/plugins/core/themes/show/show.service.ts
  backend/plugins/forum/forums/show/last_posts/dto/last_posts.args.ts
  backend/plugins/forum/forums/show/last_posts/last_posts.service.ts
  backend/plugins/forum/forums/show/show.service.ts
  backend/plugins/forum/topics/show/show.service.ts
  backend/schema.gql
  docs/pages/plugins/database/pagination.mdx
  docs/pages/plugins/database/sorting.mdx
  frontend/components/data-table/data-table.tsx
  frontend/graphql/hooks.ts
  frontend/graphql/queries/admin/members/groups/admin__core_groups__show.gql
  frontend/graphql/queries/admin/members/staff/admin__core_staff_administrators__show.gql
  frontend/graphql/queries/admin/members/staff/admin__core_staff_moderators__show.gql
  frontend/graphql/queries/admin/members/users/admin__core_members__show.gql
  frontend/graphql/queries/admin/plugins/admin__core_plugins__show.gql
  frontend/graphql/queries/admin/themes/admin__core_themes__show.gql
  frontend/graphql/queries/core/languages/core_languages__show.gql
  frontend/graphql/queries/core/members/settings/core_members__files__show.gql
Labels: 🚀 Performerce, 🚨 Breaking Changes

#323 feat: Email System
  .gitignore
  backend/plugins/core/core.module.ts
  backend/plugins/core/mail/mail.module.ts
  backend/plugins/core/mail/send/dto/mail.args.ts
  backend/plugins/core/mail/send/mail.resolver.ts
  backend/plugins/core/mail/send/mail.service.ts
  backend/schema.gql
  package.json
  pnpm-lock.yaml
Labels: 💡 Feature

#329 feat: Add turborepo
  .gitignore
  frontend/admin/blog/views/categories/table/table.tsx
  frontend/components/editor/footer/files/list.tsx
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: 💡 Feature
